export type MapMode="vector"|"cluster"|"heat"|"fade";
export type TimelinePreset="7d"|"30d"|"6m"|"1y"|"all"|"custom";
export type PlayStep="day"|"week"|"month"|"quarter";
export type MapStateRecord={date:string;confidence:string};
export type TimelineProfile={granularity:string;playStep:PlayStep;recommendedMode:MapMode;combinedHeat:boolean};

const DAY=86_400_000;
export function parseMapDate(value:string){const date=/^\d{4}-\d{2}-\d{2}$/.test(value)?new Date(`${value}T00:00:00Z`):new Date(value);return Number.isFinite(date.getTime())?date:null}
export function formatMapDate(date:Date){return date.toISOString().slice(0,10)}
export function mapDateExtent<T extends MapStateRecord>(records:T[]){const times=records.map(r=>parseMapDate(r.date)?.getTime()).filter((n):n is number=>typeof n==="number");if(!times.length){const today=formatMapDate(new Date());return {start:today,end:today}}return {start:formatMapDate(new Date(Math.min(...times))),end:formatMapDate(new Date(Math.max(...times)))}}
export function timelineRangeForPreset(preset:TimelinePreset,records:MapStateRecord[],now=new Date()){const extent=mapDateExtent(records);if(preset==="all")return extent;const end=formatMapDate(now),date=new Date(`${end}T00:00:00Z`);if(preset==="7d")date.setUTCDate(date.getUTCDate()-6);if(preset==="30d")date.setUTCDate(date.getUTCDate()-29);if(preset==="6m")date.setUTCMonth(date.getUTCMonth()-6);if(preset==="1y")date.setUTCFullYear(date.getUTCFullYear()-1);return {start:formatMapDate(date),end}}
export function timelineProfile(start:string,end:string):TimelineProfile{const a=parseMapDate(start)?.getTime()||0,b=parseMapDate(end)?.getTime()||a;const days=Math.max(1,Math.ceil((b-a)/DAY)+1);if(days<=14)return {granularity:"日 / Point / Direction",playStep:"day",recommendedMode:"vector",combinedHeat:false};if(days<=90)return {granularity:"日〜週 / Point + Cluster",playStep:"week",recommendedMode:"cluster",combinedHeat:false};if(days<=366)return {granularity:"週〜月 / Cluster",playStep:"month",recommendedMode:"cluster",combinedHeat:false};if(days<=1096)return {granularity:"月 / Cluster + Heat",playStep:"quarter",recommendedMode:"cluster",combinedHeat:true};return {granularity:"月〜年 / Heat / Aggregate",playStep:"quarter",recommendedMode:"heat",combinedHeat:false}}
export function visibleMapRecords<T extends MapStateRecord>(records:T[],confidence:string,start:string,end:string){const min=parseMapDate(start)?.getTime()??-Infinity,max=parseMapDate(end)?.getTime()??Infinity;return records.filter(record=>{const value=parseMapDate(record.date)?.getTime();return value!==undefined&&value!==null&&(confidence==="all"||record.confidence===confidence)&&value>=min&&value<=max})}
export function mapFadeOpacity(date:string,start:string,end:string,enabled:boolean){if(!enabled)return 1;const min=parseMapDate(start)?.getTime()||0,max=parseMapDate(end)?.getTime()||min,value=parseMapDate(date)?.getTime()||min;if(max<=min)return 1;const relative=Math.max(0,Math.min(1,(value-min)/(max-min)));return Number((.16+relative*.84).toFixed(3))}
export function mapModeState(mode:MapMode,combinedHeat=false){return {heatOpacity:mode==="heat"?.82:combinedHeat?.46:0,clusterOpacity:mode==="cluster"?1:0,clusterLabels:mode==="cluster"?"visible":"none",pointOpacity:mode==="heat"?.08:mode==="cluster"?0:mode==="fade"?"fade":1,pointRadius:mode==="vector"?8:mode==="fade"?7:5,directionVisibility:mode==="vector"?"visible":"none"} as const}
export function advanceTimelineWindow(start:string,end:string,step:PlayStep){const add=(value:string)=>{const d=parseMapDate(value)||new Date();if(step==="day")d.setUTCDate(d.getUTCDate()+1);if(step==="week")d.setUTCDate(d.getUTCDate()+7);if(step==="month")d.setUTCMonth(d.getUTCMonth()+1);if(step==="quarter")d.setUTCMonth(d.getUTCMonth()+3);return formatMapDate(d)};return {start:add(start),end:add(end)}}
