"use client";

import {useCallback,useMemo,useState} from "react";
import {PersonPicker} from "../components/PersonPicker";
import {subjects} from "../data/platform";
import {buildTipsSummary,canAdvanceTipsStep} from "../lib/tips-state";
import {LocationPicker} from "./location-picker";

const steps=["緊急性","いつ","どこ","観察条件","一致した点","一致しなかった点","移動","証拠","確認"] as const;
const options:Record<number,string[]>={0:["今、目の前にいる","少し前に見た","後から思い出した"],1:["今","5分前","15分前","30分前","1時間前","日時を入力"],3:["5m未満","5〜20m","20m以上","明るい屋外","暗い場所","車内から"],4:["顔","身長","体格","髪型","歩き方","声","服装","動作"],5:["服装が違う","髪型が違う","年齢の印象","身長が違う","顔の一部が違う","特になし"],6:["徒歩","自転車","バイク","車","公共交通","停止中","不明"],7:["写真あり","動画あり","防犯カメラあり","ドラレコあり","なし"]};
const multiSteps=new Set([3,4,5,7]);
type Coords={lat:string;lon:string};
type Created={state:"approved_public"|"pending";submissionId:string;editSecret:string;recoveryCode:string;managementPath:string};
function initialSlug(){if(typeof window==="undefined")return subjects[0].slug;const slug=new URLSearchParams(window.location.search).get("subject");return subjects.some(item=>item.slug===slug)?String(slug):subjects[0].slug}

export function TipsWizard({turnstileSiteKey}:{turnstileSiteKey?:string}){
 const firstSlug=initialSlug(),firstSubject=subjects.find(item=>item.slug===firstSlug)!;
 const [step,setStep]=useState(0),[subjectSlug,setSubjectSlug]=useState(firstSlug),[data,setData]=useState<Record<string,string>>({対象:firstSubject.name}),[coords,setCoords]=useState<Coords|null>(null),[notice,setNotice]=useState(""),[sending,setSending]=useState(false),[created,setCreated]=useState<Created|null>(null),[geographicPrecision,setGeographicPrecision]=useState("city"),[files,setFiles]=useState<File[]>([]),[website,setWebsite]=useState(""),[uploadResult,setUploadResult]=useState("");
 const key=steps[step],done=step===steps.length-1,current=data[key]||"",subject=subjects.find(item=>item.slug===subjectSlug);const summary=useMemo(()=>buildTipsSummary(data),[data]),required=!canAdvanceTipsStep(step,steps,data);
 const set=useCallback((value:string)=>setData(previous=>({...previous,[steps[step]]:value})),[step]);
 const toggle=(value:string)=>setData(previous=>{const list=(previous[key]||"").split("、").filter(Boolean),next=list.includes(value)?list.filter(item=>item!==value):[...list,value];return {...previous,[key]:next.join("、")}});
 function chooseSubject(slug:string){setSubjectSlug(slug);const selected=subjects.find(item=>item.slug===slug);setData(previous=>({...previous,対象:selected?.name||"対象不明"}))}
 function next(){if(required){setNotice("この項目を選択または入力してください。");return}setNotice("");setStep(value=>Math.min(value+1,steps.length-1))}
 function chooseFiles(list:FileList|null){const nextFiles=Array.from(list||[]);if(nextFiles.length>3){setNotice("添付は3ファイルまでです。");return}if(nextFiles.some(file=>file.size>25*1024*1024)||nextFiles.reduce((sum,file)=>sum+file.size,0)>50*1024*1024){setNotice("1ファイル25MB、合計50MB以内にしてください。");return}setFiles(nextFiles);setNotice("")}
 async function submit(){
  setNotice("");if(!coords){setNotice("現在地取得または地図タップで位置を指定してください。");return}
  setSending(true);const turnstileToken=document.querySelector<HTMLInputElement>('input[name="cf-turnstile-response"]')?.value||"";const payload={...data,...(files.length?{"証拠ファイル":`${files.length}件を非公開添付`}:{})};
  try{const response=await fetch("/api/tips",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({subjectSlug:subject?.slug||null,caseSlug:subject?.caseSlugs[0]||null,payload,exactLat:coords.lat,exactLon:coords.lon,geographicPrecision,temporalPrecision:/^\d{4}-\d{2}-\d{2}T/.test(data["いつ"]||"")?"exact":"period",website,turnstileToken})}),result=await response.json() as Created&{error?:string};if(!response.ok)throw new Error(result.error||"保存できませんでした。");
   if(files.length){const form=new FormData();files.forEach(file=>form.append("evidence",file,file.name));const upload=await fetch(`/api/tips/${result.submissionId}/evidence`,{method:"POST",headers:{authorization:`Bearer ${result.editSecret}`},body:form}),uploaded=await upload.json() as {error?:string;files?:unknown[]};if(!upload.ok)setUploadResult(`添付を保存できませんでした：${uploaded.error||"管理ページから再度お試しください。"}`);else setUploadResult(`${uploaded.files?.length||files.length}件を非公開保存しました。`)}
   setCreated(result)
  }catch(error){setNotice(error instanceof Error?error.message:"保存できませんでした。")}finally{setSending(false)}
 }
 function saveRecovery(){if(!created)return;const file=new Blob([`submission_id: ${created.submissionId}\nrecovery_code: ${created.recoveryCode}\n`],{type:"text/plain"}),url=URL.createObjectURL(file),anchor=document.createElement("a");anchor.href=url;anchor.download=`tip-recovery-${created.submissionId}.txt`;anchor.click();URL.revokeObjectURL(url)}
 if(created){const url=typeof window!=="undefined"?`${window.location.origin}${created.managementPath}`:created.managementPath,published=created.state==="approved_public";return <section className="wizard"><div className="submission-complete"><p className="kicker">{published?"ANONYMOUS SIGHTING / PUBLISHED":"SUBMISSION RECEIVED"}</p><h2>{published?"匿名の目撃情報を地図へ公開しました。":"匿名の目撃情報を受け付けました。"}</h2>{uploadResult&&<p role="status" className="upload-result">{uploadResult}</p>}<dl><dt>受付番号</dt><dd>{created.submissionId}</dd><dt>復旧コード</dt><dd><code>{created.recoveryCode}</code></dd></dl><div className="action-row"><button onClick={()=>navigator.clipboard.writeText(url)}>管理リンクを保存</button><button onClick={saveRecovery}>復旧コードを保存</button><a href={created.managementPath}>管理ページを開く →</a></div><p className="form-error">管理リンクと復旧コードの両方を失った場合、アカウント登録を行わないため復旧できません。</p></div></section>}

 return <section className="wizard">
  <PersonPicker value={subjectSlug} onChange={chooseSubject} includeUnknown label="目撃した可能性がある人物"/>
  <div className="wizard-progress"><span style={{width:`${((step+1)/steps.length)*100}%`}}/><p>{step+1} / {steps.length}　{key}</p></div>
  {data["緊急性"]==="今、目の前にいる"&&<div className="live-safety" role="alert"><b>サイトへの入力より安全を優先してください。</b><p>追跡しない、接触しない、安全な場所へ移動する。危険や緊急性がある場合は110番へ。</p></div>}
  {done?<div className="summary"><p className="kicker">FINAL CHECK</p><h2>入力内容を確認</h2><div className="review-summary"><pre>{summary}</pre><p>元の写真・動画は編集や圧縮をせず保存し、求められた場合に原本を提示できる状態にしてください。</p><button type="button" className="review-edit" onClick={()=>setStep(0)}>入力を修正する</button></div><label className="honeypot" aria-hidden="true">ウェブサイト<input tabIndex={-1} autoComplete="off" value={website} onChange={event=>setWebsite(event.target.value)}/></label><SavePanel geographicPrecision={geographicPrecision} setGeographicPrecision={setGeographicPrecision} files={files} chooseFiles={chooseFiles} turnstileSiteKey={turnstileSiteKey} sending={sending} submit={submit}/>{notice&&<p role="alert" className="form-error">{notice}</p>}</div>:<Question step={step} keyName={key} current={current} data={data} setData={setData} setValue={set} toggle={toggle} coords={coords} setCoords={setCoords} notice={notice} setNotice={setNotice} required={required} next={next} setStep={setStep}/>}
 </section>
}

type SaveProps={geographicPrecision:string;setGeographicPrecision:(value:string)=>void;files:File[];chooseFiles:(value:FileList|null)=>void;turnstileSiteKey?:string;sending:boolean;submit:()=>void};
function SavePanel(props:SaveProps){return <div className="save-tip"><div className="save-tip-heading"><span>09</span><div><p className="kicker">ANONYMOUS MAP ENTRY</p><h3>匿名で地図へ公開する</h3></div></div><label>地図上の公開範囲<select value={props.geographicPrecision} onChange={event=>props.setGeographicPrecision(event.target.value)}><option value="city">市区町村単位</option><option value="prefecture">都道府県単位</option><option value="region">地方単位</option></select></label><div className="evidence-upload"><label>写真・動画（任意・非公開）<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/heic,image/heif,video/mp4,video/quicktime,video/webm" onChange={event=>props.chooseFiles(event.target.files)}/></label>{props.files.map(file=><small key={`${file.name}-${file.size}`}>{file.name}　{(file.size/1024/1024).toFixed(1)}MB</small>)}</div>{props.turnstileSiteKey&&<div className="cf-turnstile" data-sitekey={props.turnstileSiteKey}/>}<div className="anonymous-submit"><button disabled={props.sending} onClick={props.submit}><span>{props.sending?"送信中…":"匿名で公開する"}</span><i aria-hidden="true">→</i></button><small>NO ACCOUNT / PUBLIC MAP</small></div></div>}

type QuestionProps={step:number;keyName:string;current:string;data:Record<string,string>;setData:React.Dispatch<React.SetStateAction<Record<string,string>>>;setValue:(value:string)=>void;toggle:(value:string)=>void;coords:Coords|null;setCoords:(value:Coords|null)=>void;notice:string;setNotice:(value:string)=>void;required:boolean;next:()=>void;setStep:React.Dispatch<React.SetStateAction<number>>};
function Question(props:QuestionProps){return <div className="wizard-card"><p className="kicker">STEP {props.step+1}</p><h2>{props.keyName}</h2>{props.step===1&&props.current==="日時を入力"&&<input type="datetime-local" aria-label="目撃日時" onChange={event=>event.target.value&&props.setValue(event.target.value)}/>} {props.step===2?<><div className="chips"><button onClick={()=>navigator.geolocation?.getCurrentPosition(position=>{const lat=position.coords.latitude.toFixed(5),lon=position.coords.longitude.toFixed(5);props.setCoords({lat,lon});props.setValue(`${lat}, ${lon}（端末で取得）`)},()=>props.setNotice("現在地を取得できませんでした。地図または目印で指定してください。"))}>現在地を明示取得</button></div><input placeholder="駅名・施設名・目印" value={props.current.includes("（")?"":props.current} onChange={event=>props.setValue(event.target.value)}/><LocationPicker selected={props.coords} onPick={(value,location)=>{props.setCoords(location);props.setValue(value)}} onReset={()=>{props.setCoords(null);props.setValue("")}}/></>:props.step===6?<><div className="chips">{options[props.step].map(item=><button className={(props.data["移動手段"]||"")===item?"selected":""} onClick={()=>props.setData(previous=>({...previous,"移動手段":item}))} key={item}>{item}</button>)}</div><p>移動した方向</p><div className="direction-grid">{["北西","北","北東","西","不明","東","南西","南","南東"].map(item=><button className={(props.data["移動方向"]||"")===item?"selected":""} onClick={()=>props.setData(previous=>({...previous,"移動方向":item,[props.keyName]:`${previous["移動手段"]||"手段不明"} / ${item}`}))} key={item}>{item}</button>)}</div></>:<div className="chips">{options[props.step]?.map(item=><button className={(multiSteps.has(props.step)?props.current.split("、").includes(item):props.current===item)?"selected":""} onClick={()=>multiSteps.has(props.step)?props.toggle(item):props.setValue(item)} key={item}>{item}</button>)}</div>}<textarea aria-label="補足" placeholder="必要な場合だけ補足（任意）。音声入力対応ブラウザではキーボードの音声入力も利用できます。" onBlur={event=>{const value=event.currentTarget.value.trim();if(value)props.setData(previous=>({...previous,[`${props.keyName}・補足`]:value}))}}/><div className="wizard-nav"><button disabled={props.step===0} onClick={()=>{props.setNotice("");props.setStep(value=>value-1)}}>戻る</button><button disabled={props.required} onClick={props.next}>次へ</button></div>{props.notice&&<p role="alert" className="form-error">{props.notice}</p>}</div>}
