import {runtimeEnv,writeAudit} from "./platform-db";

export type AnalyticsVisitor={visitor_hash:string;display_id:string;excluded:number;first_seen_at:string;last_seen_at:string;total_views:number};
export type AnalyticsEvent={id:string;visitor_hash:string;display_id:string;path:string;referrer_path:string|null;dwell_seconds:number;created_at:string};

async function database(){const env=await runtimeEnv();if(!env.DB||!env.TREND_HMAC_SECRET)throw new Error("analytics unavailable");return {db:env.DB,secret:env.TREND_HMAC_SECRET}}
async function hmac(input:string,secret:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]),signature=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(input));return [...new Uint8Array(signature)].map(value=>value.toString(16).padStart(2,"0")).join("")}
export async function visitorIdentity(browserId:string){const {secret}=await database(),hash=await hmac(`analytics:${browserId}`,secret);return {hash,displayId:`訪問者 ${hash.slice(0,8).toUpperCase()}`}}

export async function recordAnalyticsView(input:{browserId:string;path:string;referrerPath:string|null;dwellSeconds:number;sampleRate:number}){
 const {db,secret}=await database(),identity=await visitorIdentity(input.browserId),existing=await db.prepare("SELECT excluded FROM analytics_visitors WHERE visitor_hash=?").bind(identity.hash).first<{excluded:number}>();if(Boolean(existing?.excluded))return {accepted:false,reason:"excluded",displayId:identity.displayId};
 const rate=Math.max(0,Math.min(1,input.sampleRate)),sample=await hmac(`${new Date().toISOString().slice(0,10)}:${identity.hash}:${input.path}`,secret);if(parseInt(sample.slice(0,8),16)/0xffffffff>rate)return {accepted:false,reason:"not_sampled",displayId:identity.displayId};
 const duplicate=await db.prepare("SELECT id FROM analytics_events WHERE visitor_hash=? AND path=? AND created_at>=date('now') LIMIT 1").bind(identity.hash,input.path).first();if(duplicate)return {accepted:false,reason:"duplicate",displayId:identity.displayId};
 const recent=await db.prepare("SELECT COUNT(*) AS count FROM analytics_events WHERE visitor_hash=? AND created_at>=datetime('now','-1 minute')").bind(identity.hash).first<{count:number}>();if(Number(recent?.count||0)>=20)return {accepted:false,reason:"rate_limited",displayId:identity.displayId};
 await db.batch([db.prepare("INSERT INTO analytics_visitors (visitor_hash,display_id,excluded,first_seen_at,last_seen_at,total_views) VALUES (?,?,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1) ON CONFLICT(visitor_hash) DO UPDATE SET last_seen_at=CURRENT_TIMESTAMP,total_views=total_views+1").bind(identity.hash,identity.displayId),db.prepare("INSERT INTO analytics_events (id,visitor_hash,path,referrer_path,dwell_seconds,created_at) VALUES (?,?,?,?,?,CURRENT_TIMESTAMP)").bind(crypto.randomUUID(),identity.hash,input.path,input.referrerPath,Math.floor(input.dwellSeconds))]);return {accepted:true,displayId:identity.displayId};
}

export async function listAnalyticsForAdmin(browserId?:string|null){
 const {db}=await database();let currentVisitorId:string|null=null;if(browserId){const identity=await visitorIdentity(browserId);currentVisitorId=identity.displayId;await db.prepare("INSERT OR IGNORE INTO analytics_visitors (visitor_hash,display_id,excluded,first_seen_at,last_seen_at,total_views) VALUES (?,?,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0)").bind(identity.hash,identity.displayId).run()}
 const [visitors,events]=await Promise.all([db.prepare("SELECT visitor_hash,display_id,excluded,first_seen_at,last_seen_at,total_views FROM analytics_visitors ORDER BY excluded ASC,last_seen_at DESC LIMIT 300").all<AnalyticsVisitor>(),db.prepare("SELECT e.id,e.visitor_hash,v.display_id,e.path,e.referrer_path,e.dwell_seconds,e.created_at FROM analytics_events e JOIN analytics_visitors v ON v.visitor_hash=e.visitor_hash WHERE v.excluded=0 ORDER BY e.created_at DESC LIMIT 1000").all<AnalyticsEvent>()]);return {currentVisitorId,visitors:visitors.results,events:events.results};
}

export async function setAnalyticsExclusion(input:{browserId?:string|null;visitorHash?:string|null;excluded:boolean},actor:string){const {db}=await database();let hash=input.visitorHash||null,displayId:string|null=null;if(input.browserId){const identity=await visitorIdentity(input.browserId);hash=identity.hash;displayId=identity.displayId;await db.prepare("INSERT OR IGNORE INTO analytics_visitors (visitor_hash,display_id,excluded,first_seen_at,last_seen_at,total_views) VALUES (?,?,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0)").bind(hash,displayId).run()}if(!hash)return false;const existing=await db.prepare("SELECT display_id FROM analytics_visitors WHERE visitor_hash=?").bind(hash).first<{display_id:string}>();if(!existing)return false;await db.prepare("UPDATE analytics_visitors SET excluded=? WHERE visitor_hash=?").bind(input.excluded?1:0,hash).run();await writeAudit(actor,input.excluded?"analytics_exclude":"analytics_include","analytics_visitor",existing.display_id,"browser identifier excluded from analytics totals and history");return true}
