import {runtimeEnv,saveContent,writeAudit} from "./platform-db";

export type TipState="draft"|"pending"|"under_review"|"approved_public"|"rejected"|"withdrawn"|"deleted";
export type GeographicPrecision="point"|"city"|"prefecture"|"region";
export type TemporalPrecision="exact"|"day"|"month"|"period";
export type TipSubmission={id:string;state:TipState;subjectSlug:string|null;caseSlug:string|null;payload:Record<string,string>;exactLat:string|null;exactLon:string|null;publicLat:string|null;publicLon:string|null;requestedPublicPrecision:GeographicPrecision;geographicPrecision:GeographicPrecision;temporalPrecision:TemporalPrecision;recordType:string;revision:number;createdAt:string;updatedAt:string;approvedAt:string|null;withdrawnAt:string|null};
export type TipPrivateContact={submissionId:string;email:string|null;phone:string|null;consent:boolean};
export type TipEvidenceMeta={id:string;submissionId:string;originalFilename:string;mime:string;fileSize:number;sha256:string;status:string;reviewState:string;uploadedAt:string};

async function database(){const env=await runtimeEnv();if(!env.DB)throw new Error("D1 unavailable");return env.DB}
function rowToTip(row:Record<string,unknown>):TipSubmission{return {id:String(row.id),state:String(row.state) as TipState,subjectSlug:row.subject_slug?String(row.subject_slug):null,caseSlug:row.case_slug?String(row.case_slug):null,payload:JSON.parse(String(row.payload||"{}")),exactLat:row.exact_lat?String(row.exact_lat):null,exactLon:row.exact_lon?String(row.exact_lon):null,publicLat:row.public_lat?String(row.public_lat):null,publicLon:row.public_lon?String(row.public_lon):null,requestedPublicPrecision:String(row.requested_public_precision||row.geographic_precision) as GeographicPrecision,geographicPrecision:String(row.geographic_precision) as GeographicPrecision,temporalPrecision:String(row.temporal_precision) as TemporalPrecision,recordType:String(row.record_type),revision:Number(row.revision),createdAt:String(row.created_at),updatedAt:String(row.updated_at),approvedAt:row.approved_at?String(row.approved_at):null,withdrawnAt:row.withdrawn_at?String(row.withdrawn_at):null}}
export function randomSecret(bytes=32){const values=new Uint8Array(bytes);crypto.getRandomValues(values);return btoa(String.fromCharCode(...values)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
export async function hashTipSecret(value:string,pepper:string){const bytes=new TextEncoder().encode(`${pepper}:${value}`),digest=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,"0")).join("")}
function safeHashEqual(a:string,b:string){if(a.length!==b.length)return false;let difference=0;for(let index=0;index<a.length;index++)difference|=a.charCodeAt(index)^b.charCodeAt(index);return difference===0}

export async function createTip(input:{subjectSlug?:string|null;caseSlug?:string|null;payload:Record<string,string>;exactLat?:string|null;exactLon?:string|null;geographicPrecision:GeographicPrecision;temporalPrecision:TemporalPrecision;recordType:string;contact?:{enabled:boolean;email?:string|null;phone?:string|null}},pepper:string){
 const d1=await database(),id=crypto.randomUUID(),editSecret=randomSecret(32),recoveryCode=randomSecret(18),secretHash=await hashTipSecret(editSecret,pepper),recoveryHash=await hashTipSecret(recoveryCode,pepper);
 const statements=[d1.prepare("INSERT INTO tip_submissions (id,secret_hash,recovery_hash,state,subject_slug,case_slug,payload,exact_lat,exact_lon,requested_public_precision,geographic_precision,temporal_precision,record_type,revision,created_at,updated_at) VALUES (?,?,?,'pending',?,?,?,?,?,?,?,?,?,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").bind(id,secretHash,recoveryHash,input.subjectSlug||null,input.caseSlug||null,JSON.stringify(input.payload),input.exactLat||null,input.exactLon||null,input.geographicPrecision,input.geographicPrecision,input.temporalPrecision,input.recordType)];
 if(input.contact?.enabled)statements.push(d1.prepare("INSERT INTO tip_private_contacts (submission_id,email,phone,consent,created_at,updated_at) VALUES (?,?,?,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").bind(id,input.contact.email||null,input.contact.phone||null));
 await d1.batch(statements);await writeAudit("anonymous","create","tip_submission",id,JSON.stringify({state:"pending",requestedPublicPrecision:input.geographicPrecision,temporalPrecision:input.temporalPrecision,privateContact:Boolean(input.contact?.enabled)}));return {id,editSecret,recoveryCode};
}
export async function authorizedTip(id:string,secret:string,pepper:string){const d1=await database(),row=await d1.prepare("SELECT * FROM tip_submissions WHERE id=?").bind(id).first<Record<string,unknown>>();if(!row)return null;const hash=await hashTipSecret(secret,pepper);return safeHashEqual(hash,String(row.secret_hash))?rowToTip(row):null}
export async function rotateTipSecret(id:string,recoveryCode:string,pepper:string){const d1=await database(),row=await d1.prepare("SELECT recovery_hash,state FROM tip_submissions WHERE id=?").bind(id).first<{recovery_hash:string;state:string}>();if(!row||row.state==="deleted")return null;const hash=await hashTipSecret(recoveryCode,pepper);if(!safeHashEqual(hash,row.recovery_hash))return null;const editSecret=randomSecret(32),secretHash=await hashTipSecret(editSecret,pepper);await d1.prepare("UPDATE tip_submissions SET secret_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(secretHash,id).run();await writeAudit("anonymous-recovery","rotate_secret","tip_submission",id,"management secret rotated");return editSecret}
export async function editTip(id:string,secret:string,pepper:string,payload:Record<string,string>){const existing=await authorizedTip(id,secret,pepper);if(!existing)return {kind:"unauthorized" as const};const d1=await database();if(existing.state==="pending"||existing.state==="draft"){await d1.prepare("UPDATE tip_submissions SET payload=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(JSON.stringify(payload),id).run();await writeAudit("anonymous","edit_pending","tip_submission",id,JSON.stringify({revision:existing.revision+1}));return {kind:"updated" as const}}if(existing.state==="approved_public"){const revisionNo=existing.revision+1;await d1.prepare("INSERT INTO tip_revisions (id,submission_id,revision_no,payload,state,created_at) VALUES (?,?,?,?,'revision_pending',CURRENT_TIMESTAMP)").bind(crypto.randomUUID(),id,revisionNo,JSON.stringify(payload)).run();await writeAudit("anonymous","revision_pending","tip_submission",id,JSON.stringify({revision:revisionNo}));return {kind:"revision_pending" as const}}return {kind:"locked" as const,state:existing.state}}
export async function withdrawTip(id:string,secret:string,pepper:string){const existing=await authorizedTip(id,secret,pepper);if(!existing||existing.state==="deleted")return false;const d1=await database();await d1.batch([d1.prepare("UPDATE tip_submissions SET state='withdrawn',withdrawn_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(id),d1.prepare("UPDATE content_records SET publish_state='withdrawn',withdrawn_at=CURRENT_TIMESTAMP,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(`map:tip-${id}`)]);await writeAudit("anonymous","withdraw","tip_submission",id,"public record removed; audit retained");return true}

function evidenceRow(row:Record<string,unknown>):TipEvidenceMeta{return {id:String(row.id),submissionId:String(row.submission_id),originalFilename:String(row.original_filename),mime:String(row.mime),fileSize:Number(row.file_size),sha256:String(row.sha256),status:String(row.status),reviewState:String(row.review_state||"pending"),uploadedAt:String(row.uploaded_at)}}
export async function listTipsForAdmin(){const d1=await database();const [submissions,revisions,contacts,evidence]=await Promise.all([d1.prepare("SELECT * FROM tip_submissions ORDER BY updated_at DESC LIMIT 300").all<Record<string,unknown>>(),d1.prepare("SELECT id,submission_id,revision_no,payload,state,created_at,reviewed_at,reviewed_by FROM tip_revisions ORDER BY created_at DESC LIMIT 300").all<Record<string,unknown>>(),d1.prepare("SELECT submission_id,email,phone,consent FROM tip_private_contacts ORDER BY updated_at DESC LIMIT 300").all<Record<string,unknown>>(),d1.prepare("SELECT id,submission_id,original_filename,mime,file_size,sha256,status,review_state,uploaded_at FROM tip_evidence ORDER BY uploaded_at DESC LIMIT 600").all<Record<string,unknown>>()]);return {submissions:submissions.results.map(rowToTip),revisions:revisions.results.map(row=>({...row,payload:JSON.parse(String(row.payload||"{}"))})),contacts:contacts.results.map(row=>({submissionId:String(row.submission_id),email:row.email?String(row.email):null,phone:row.phone?String(row.phone):null,consent:Boolean(row.consent)})),evidence:evidence.results.map(evidenceRow)}}
export async function privateTipDetails(id:string){const d1=await database();const [contact,evidence]=await Promise.all([d1.prepare("SELECT submission_id,email,phone,consent FROM tip_private_contacts WHERE submission_id=?").bind(id).first<Record<string,unknown>>(),d1.prepare("SELECT id,submission_id,original_filename,mime,file_size,sha256,status,review_state,uploaded_at FROM tip_evidence WHERE submission_id=? ORDER BY uploaded_at").bind(id).all<Record<string,unknown>>()]);return {contact:contact?{submissionId:String(contact.submission_id),email:contact.email?String(contact.email):null,phone:contact.phone?String(contact.phone):null,consent:Boolean(contact.consent)}:null,evidence:evidence.results.map(evidenceRow)}}
export async function addEvidenceMetadata(input:{id:string;submissionId:string;objectKey:string;originalFilename:string;mime:string;fileSize:number;sha256:string}){const d1=await database();await d1.prepare("INSERT INTO tip_evidence (id,submission_id,object_key,original_filename,mime,file_size,sha256,status,review_state,uploaded_at) VALUES (?,?,?,?,?,?,?,'private','pending',CURRENT_TIMESTAMP)").bind(input.id,input.submissionId,input.objectKey,input.originalFilename,input.mime,input.fileSize,input.sha256).run();await writeAudit("anonymous","evidence_upload","tip_submission",input.submissionId,JSON.stringify({evidenceId:input.id,mime:input.mime,fileSize:input.fileSize,sha256:input.sha256,reviewState:"pending"}));return input.id}
export async function evidenceObjectForAdmin(id:string){const d1=await database();return d1.prepare("SELECT id,submission_id,object_key,original_filename,mime,file_size,sha256,status,review_state,uploaded_at FROM tip_evidence WHERE id=?").bind(id).first<Record<string,unknown>>()}
export async function evidenceObjectKeysForSubmission(id:string){const d1=await database(),rows=await d1.prepare("SELECT object_key FROM tip_evidence WHERE submission_id=?").bind(id).all<{object_key:string}>();return rows.results.map(row=>row.object_key)}

function roundedCoordinate(value:string|null,precision:GeographicPrecision){if(!value)return null;const number=Number(value);if(!Number.isFinite(number))return null;const digits=precision==="point"?3:precision==="city"?2:precision==="prefecture"?1:0;return number.toFixed(digits)}
function directionFromText(value=""){return value.includes("北東")?45:value.includes("東")?90:value.includes("南東")?135:value.includes("南")?180:value.includes("南西")?225:value.includes("西")?270:value.includes("北西")?315:0}
function publicMapPayload(tip:TipSubmission,payload=tip.payload){const lat=tip.publicLat||roundedCoordinate(tip.exactLat,tip.geographicPrecision),lon=tip.publicLon||roundedCoordinate(tip.exactLon,tip.geographicPrecision);if(!lat||!lon)return null;return {id:`tip-${tip.id}`,subject:tip.subjectSlug||"unknown",caseSlug:tip.caseSlug||"unknown",label:`匿名目撃情報（${tip.geographicPrecision}単位）`,lat:Number(lat),lon:Number(lon),date:tip.createdAt.slice(0,10),dateLabel:payload["いつ"]||"期間情報あり",temporalPrecision:tip.temporalPrecision,geographicPrecision:tip.geographicPrecision,confidence:"MED",source:"approved_public",recordType:"approved_public",direction:directionFromText(payload["移動"]||payload["移動方向"]||"")}}
const precisionRank:Record<GeographicPrecision,number>={point:0,city:1,prefecture:2,region:3};
async function publishedWanted(d1:D1Database,slug:string|null){if(!slug)return false;return Boolean(await d1.prepare("SELECT id FROM content_records WHERE kind='wanted' AND slug=? AND publish_state='published'").bind(slug).first())}

export async function moderateTip(input:{id:string;action:"review"|"approve"|"reject"|"approve_revision"|"withdraw";revisionId?:string;publicPrecision?:GeographicPrecision},actor:string){
 const d1=await database(),row=await d1.prepare("SELECT * FROM tip_submissions WHERE id=?").bind(input.id).first<Record<string,unknown>>();if(!row)return false;const tip=rowToTip(row);if(tip.state==="deleted")return false;
 if(input.action==="review"){await d1.prepare("UPDATE tip_submissions SET state='under_review',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(input.id).run();await writeAudit(actor,"under_review","tip_submission",input.id,"moderation started");return true}
 if(input.action==="reject"||input.action==="withdraw"){const state=input.action==="reject"?"rejected":"withdrawn";await d1.batch([d1.prepare("UPDATE tip_submissions SET state=?,withdrawn_at=CASE WHEN ?='withdrawn' THEN CURRENT_TIMESTAMP ELSE withdrawn_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(state,state,input.id),d1.prepare("UPDATE content_records SET publish_state='withdrawn',withdrawn_at=CURRENT_TIMESTAMP,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(`map:tip-${input.id}`)]);await writeAudit(actor,input.action,"tip_submission",input.id,"public map record removed; audit retained");return true}
 if(!await publishedWanted(d1,tip.subjectSlug))throw new Error("対象不明または未公開人物の目撃情報は公開できません。公式人物レコードを公開してから紐付けてください");
 const publicPrecision=input.publicPrecision||tip.geographicPrecision;if(precisionRank[publicPrecision]<precisionRank[tip.requestedPublicPrecision])throw new Error("公開位置精度を投稿者の希望より細かくすることはできません");
 const publicTip={...tip,geographicPrecision:publicPrecision};let payload=tip.payload;const revisionId=input.revisionId;
 if(input.action==="approve_revision"){if(!revisionId)return false;const revision=await d1.prepare("SELECT payload FROM tip_revisions WHERE id=? AND submission_id=? AND state='revision_pending'").bind(revisionId,input.id).first<{payload:string}>();if(!revision)return false;payload=JSON.parse(revision.payload)}
 const mapPayload=publicMapPayload(publicTip,payload);if(!mapPayload)throw new Error("公開用座標がないため承認できません");
 await saveContent({id:`map:tip-${tip.id}`,kind:"map",slug:`tip-${tip.id}`,title:String(mapPayload.label),payload:mapPayload,publishState:"published",correctionNote:input.action==="approve_revision"?"投稿者Revisionを審査承認":undefined},actor);
 if(input.action==="approve_revision")await d1.batch([d1.prepare("UPDATE tip_revisions SET state='approved',reviewed_at=CURRENT_TIMESTAMP,reviewed_by=? WHERE id=?").bind(actor,revisionId),d1.prepare("UPDATE tip_submissions SET payload=?,geographic_precision=?,public_lat=?,public_lon=?,revision=revision+1,state='approved_public',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(JSON.stringify(payload),publicPrecision,String(mapPayload.lat),String(mapPayload.lon),input.id)]);else await d1.prepare("UPDATE tip_submissions SET state='approved_public',geographic_precision=?,public_lat=?,public_lon=?,approved_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(publicPrecision,String(mapPayload.lat),String(mapPayload.lon),input.id).run();
 await writeAudit(actor,input.action,"tip_submission",input.id,JSON.stringify({publicRecord:`map:tip-${tip.id}`,revisionId,requestedPublicPrecision:tip.requestedPublicPrecision,publicPrecision}));return true;
}

export async function adminUpdateTip(input:{id:string;subjectSlug:string|null;caseSlug:string|null;payload:Record<string,string>;exactLat:string|null;exactLon:string|null;publicPrecision:GeographicPrecision},actor:string){
 const d1=await database(),row=await d1.prepare("SELECT * FROM tip_submissions WHERE id=?").bind(input.id).first<Record<string,unknown>>();if(!row)return false;const tip=rowToTip(row);if(tip.state==="deleted")throw new Error("削除済み目撃情報は編集できません");
 if(input.subjectSlug&&!await d1.prepare("SELECT id FROM content_records WHERE kind='wanted' AND slug=? AND publish_state!='withdrawn'").bind(input.subjectSlug).first())throw new Error("指定した人物レコードが存在しません");
 if(input.caseSlug&&!await d1.prepare("SELECT id FROM content_records WHERE kind='case' AND slug=? AND publish_state!='withdrawn'").bind(input.caseSlug).first())throw new Error("指定した事件レコードが存在しません");
 if(precisionRank[input.publicPrecision]<precisionRank[tip.requestedPublicPrecision])throw new Error("投稿者の希望より細かい位置精度には変更できません");
 const updated:TipSubmission={...tip,subjectSlug:input.subjectSlug,caseSlug:input.caseSlug,payload:input.payload,exactLat:input.exactLat,exactLon:input.exactLon,publicLat:null,publicLon:null,geographicPrecision:input.publicPrecision};
 let publicLat:string|null=null,publicLon:string|null=null;
 if(tip.state==="approved_public"){
  if(!await publishedWanted(d1,input.subjectSlug))throw new Error("公開中の目撃情報は、公開済み公式人物への紐付けが必要です");
  const mapPayload=publicMapPayload(updated);if(!mapPayload)throw new Error("公開用座標がないため更新できません");publicLat=String(mapPayload.lat);publicLon=String(mapPayload.lon);
  await saveContent({id:`map:tip-${tip.id}`,kind:"map",slug:`tip-${tip.id}`,title:String(mapPayload.label),payload:mapPayload,publishState:"published",correctionNote:"管理者による目撃情報修正"},actor);
 }
 await d1.prepare("UPDATE tip_submissions SET subject_slug=?,case_slug=?,payload=?,exact_lat=?,exact_lon=?,geographic_precision=?,public_lat=?,public_lon=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(input.subjectSlug,input.caseSlug,JSON.stringify(input.payload),input.exactLat,input.exactLon,input.publicPrecision,publicLat,publicLon,input.id).run();
 await writeAudit(actor,"admin_update","tip_submission",input.id,JSON.stringify({subjectSlug:input.subjectSlug,caseSlug:input.caseSlug,publicPrecision:input.publicPrecision,publicUpdated:tip.state==="approved_public"}));return true;
}

export async function adminDeleteTip(id:string,actor:string){
 const d1=await database(),row=await d1.prepare("SELECT id,state FROM tip_submissions WHERE id=?").bind(id).first<{id:string;state:string}>();if(!row)return false;if(row.state==="deleted")return true;
 await d1.batch([d1.prepare("DELETE FROM tip_private_contacts WHERE submission_id=?").bind(id),d1.prepare("DELETE FROM tip_revisions WHERE submission_id=?").bind(id),d1.prepare("DELETE FROM tip_evidence WHERE submission_id=?").bind(id),d1.prepare("DELETE FROM tip_security_logs WHERE submission_id=?").bind(id),d1.prepare("UPDATE tip_submissions SET state='deleted',subject_slug=NULL,case_slug=NULL,payload='{}',exact_lat=NULL,exact_lon=NULL,public_lat=NULL,public_lon=NULL,secret_hash=?,recovery_hash=?,withdrawn_at=CURRENT_TIMESTAMP,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(`deleted:${crypto.randomUUID()}`,`deleted:${crypto.randomUUID()}`,id),d1.prepare("UPDATE content_records SET publish_state='withdrawn',withdrawn_at=CURRENT_TIMESTAMP,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(`map:tip-${id}`)]);
 await writeAudit(actor,"delete_and_redact","tip_submission",id,"private payload, coordinates, contact, revisions and evidence metadata removed; audit shell retained");return true;
}
