"use client";import Link from "next/link";import {SearchPanel} from "./SearchPanel";import {usePublicData} from "./usePublicData";import {useEffect,useState} from "react";
import {useWantedSearchRanking} from "./useWantedSearchRanking";
type Metric={entity_type:string;entity_id:string;views:number};
export function HomeContent(){
 const data=usePublicData(),rankedSubjects=useWantedSearchRanking(data.subjects);const [metrics,setMetrics]=useState<Metric[]>([]);
 useEffect(()=>{fetch("/api/trend").then(r=>r.json()).then((j:{metrics?:Metric[]})=>setMetrics(j.metrics||[])).catch(()=>{})},[]);
 const ranked=metrics.filter(m=>m.entity_type==="wanted").map(m=>({m,s:data.subjects.find(x=>x.slug===m.entity_id)})).filter(x=>x.s);
 return <div className="home-body">
  <section className="purpose-intro" aria-labelledby="purpose-title"><p className="kicker">PUBLIC RECORDS / CITIZEN SIGHTINGS</p><h2 id="purpose-title">公開情報と、<br/>あなたの目撃をつなぐ。</h2><div className="purpose-copy"><p>警察が公開する指名手配情報と、<br/>市民から寄せられた目撃記録を人物・場所・時間でつなぎます。</p><p>「見たかもしれない」情報はアカウント不要で匿名入力。<br/>審査を通過した公開可能な範囲だけが地図へ反映されます。</p></div><nav className="purpose-links purpose-links--primary" aria-label="主な利用方法"><Link href="/tips" prefetch>目撃情報を入力する →</Link><Link href="/wanted" prefetch>公開情報を探す →</Link></nav><p className="immediate-safety"><b>似た人物が今、目の前にいる場合</b>　追跡・接触はせず、安全を確保し、必要に応じて110番を優先してください。サイトへの入力はその後で構いません。</p></section>
  <section className="role-path" aria-labelledby="role-title"><h2 id="role-title" className="sr-only">このサイトでできること</h2><article><span>01</span><div><h3>公開情報を知る</h3><p>警察庁・都道府県警察等が公開している人物と事件を確認。</p></div></article><article><span>02</span><div><h3>目撃情報を入力</h3><p>時間・場所・一致点と違和感を、質問に沿って匿名入力。</p></div></article><article><span>03</span><div><h3>匿名で地図へ</h3><p>位置を概略化した目撃記録を、送信後すぐ地図へ反映。</p></div></article><p className="role-note">正確な入力位置・写真・動画は公開しません。緊急時は110番を優先してください。</p></section>
  <SearchPanel/>
  <section className="editorial-section"><div className="section-head"><div><p className="kicker">OFFICIAL CLASSIFICATION / COMPLETE 10</p><h2>警察庁指定重要指名手配</h2></div><Link href="/wanted" prefetch>公式掲載中の10人を見る →</Link></div><p className="ranking-note">人物は過去7日間の匿名・重複抑制した検索傾向順です。</p><div className="broken-list">{rankedSubjects.map((s,i)=><Link href={`/wanted/${s.slug}`} prefetch key={s.slug}><strong>{String(i+1).padStart(2,"0")}</strong><span><b>{s.name}</b><small>{s.reading}</small></span><em>{s.agency}<br/>{s.lastVerified} 確認</em></Link>)}</div></section>
  <section className="editorial-section trend-section"><div className="section-head"><div><p className="kicker">PRIVACY PRESERVING TREND</p><h2>サイト内の閲覧傾向</h2></div><p className="section-note">警察の捜査優先度・危険度ではありません。8秒以上の閲覧だけを日次重複排除・標本化して集計します。</p></div>{ranked.length?<div className="trend-ranks">{ranked.slice(0,3).map(({m,s},i)=><Link href={`/wanted/${s!.slug}`} key={s!.slug}><span>0{i+1}</span><b>{s!.name}</b><small>標本閲覧 {m.views}件</small></Link>)}</div>:<p className="empty">集計対象となる閲覧はまだありません。</p>}</section>
  <section className="editorial-section"><div className="section-head"><div><p className="kicker">RECENTLY VERIFIED</p><h2>最近公式情報を確認した案件</h2></div></div><div className="case-lines">{data.cases.map(c=><Link href={`/cases/${c.slug}`} key={c.slug}><time>{c.date}</time><b>{c.title}</b><span>{c.prefecture} / {c.status}</span></Link>)}</div></section>
  <section className="region-map-cta"><div><p className="kicker">SEARCH BY REGION</p><h2>地域から探す</h2><p>全国の公開情報を、都道府県・事件・人物の関係からたどれます。</p><div className="region-links">{["北海道・東北","関東","中部","近畿","中国・四国","九州・沖縄"].map(x=><Link href={`/wanted?region=${encodeURIComponent(x)}`} key={x}>{x}</Link>)}</div></div><Link className="map-portal" href="/map"><span>WORLD → JAPAN → REGION</span><b>地図で辿る</b><em>方向 / 集約 / 分布 / 時間差</em></Link></section>
 </div>
}
