"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {subjects as defaultSubjects,type Subject} from "../data/platform";
import {recordWantedSearch,useWantedSearchRanking} from "./useWantedSearchRanking";

export function PersonPicker({value,onChange,includeAll=false,includeUnknown=false,label="対象人物",items=defaultSubjects}:{value:string;onChange:(slug:string)=>void;includeAll?:boolean;includeUnknown?:boolean;label?:string;items?:Subject[]}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState("");
 const root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);
 const rankedItems=useWantedSearchRanking(items),selected=rankedItems.find(item=>item.slug===value);
 const matches=useMemo(()=>rankedItems.filter(item=>[item.name,item.reading,item.classification,item.agency].join(" ").toLowerCase().includes(query.trim().toLowerCase())),[rankedItems,query]);
 function choose(next:string){if(next!=="all"&&next!=="unknown")recordWantedSearch(next);onChange(next);setOpen(false);setQuery("");trigger.current?.focus()}
 function moveOption(direction:1|-1){const items=[...(root.current?.querySelectorAll<HTMLButtonElement>('[role="option"]')||[])];if(!items.length)return;const index=items.indexOf(document.activeElement as HTMLButtonElement),next=index<0?(direction===1?0:items.length-1):(index+direction+items.length)%items.length;items[next]?.focus()}
 useEffect(()=>{const onPointer=(event:PointerEvent)=>{if(!root.current?.contains(event.target as Node))setOpen(false)};document.addEventListener("pointerdown",onPointer);return()=>document.removeEventListener("pointerdown",onPointer)},[]);
 return <div ref={root} className="person-picker" onKeyDown={event=>{if(event.key==="Escape"){setOpen(false);trigger.current?.focus()}else if(event.key==="ArrowDown"){event.preventDefault();if(!open){setOpen(true);setTimeout(()=>moveOption(1))}else moveOption(1)}else if(event.key==="ArrowUp"){event.preventDefault();if(!open){setOpen(true);setTimeout(()=>moveOption(-1))}else moveOption(-1)}}}><span className="person-picker-label">{label}</span><button ref={trigger} type="button" className="person-picker-trigger" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(current=>!current)}>{selected?<><PhotoState status={selected.photoUsageStatus}/><span><b>{selected.name}</b><small>{selected.reading} / {selected.agency}</small></span></>:<><PhotoState status={value==="all"?"all":"unknown"}/><span><b>{value==="all"?"全国・全人物":"対象不明"}</b><small>{value==="all"?"公開中の対象を横断":"人物を特定できない"}</small></span></>}<i aria-hidden="true">⌄</i></button>{open&&<div className="person-picker-popover"><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="氏名・よみ・手配元で検索" aria-label="対象人物を検索"/><div role="listbox" aria-label={label}>{includeAll&&<button type="button" role="option" aria-selected={value==="all"} onClick={()=>choose("all")}><PhotoState status="all"/><span><b>全国・全人物</b><small>すべての公開人物</small></span></button>}{matches.map(item=><button type="button" role="option" aria-selected={value===item.slug} onClick={()=>choose(item.slug)} key={item.slug}><PhotoState status={item.photoUsageStatus}/><span><b>{item.name}</b><small>{item.reading}<br/>{item.classification} / {item.agency}</small></span></button>)}{includeUnknown&&<button type="button" role="option" aria-selected={value==="unknown"} onClick={()=>choose("unknown")}><PhotoState status="unknown"/><span><b>対象不明</b><small>人物を特定できない場合</small></span></button>}</div><p>過去7日間の匿名・重複抑制した検索傾向順です。公式写真は人物ページで確認できます。</p></div>}</div>
}
function PhotoState({status}:{status:string}){return <span className={`photo-state photo-state--${status}`}>{status==="cleared_for_reuse"?"写真":status==="all"?"ALL":status==="unknown"?"?":"公式"}</span>}
