import assert from "node:assert/strict";
import {readFile,stat} from "node:fs/promises";
import test from "node:test";
import {advanceTimelineWindow,mapFadeOpacity,mapModeState,timelineProfile,visibleMapRecords} from "../app/lib/map-state.ts";
import {buildTipsSummary,canAdvanceTipsStep} from "../app/lib/tips-state.ts";
import {evidenceType} from "../app/server/evidence.ts";
import {sortByWantedSearch} from "../app/components/useWantedSearchRanking.ts";

const env={ASSETS:{fetch:async()=>new Response("Not found",{status:404})}};
const ctx={waitUntil(){},passThroughOnException(){}};
async function builtWorker(){const workerUrl=new URL("../dist/server/index.js",import.meta.url);workerUrl.searchParams.set("routes",`${process.pid}-${Date.now()}`);return (await import(workerUrl.href)).default}

test("normal public routes render through one shared public layout without query parameters",async()=>{const worker=await builtWorker();const expected=new Map([["/","見えない輪郭が、"],["/wanted","指名手配・公開捜査人物"],["/map","地図で辿る"],["/tips","目撃情報を入力する"],["/contact","運営への問い合わせ"],["/about","公開情報を辿り、目撃を正しく届ける"],["/cases","事件から探す"],["/sources","公式情報源"],["/privacy","プライバシーポリシー"],["/terms","利用規約"],["/security","セキュリティ・脆弱性報告"]]);for(const [path,h1] of expected){const response=await worker.fetch(new Request(`http://localhost${path}`,{headers:{accept:"text/html"}}),env,ctx);assert.equal(response.status,200,path);assert.match(response.headers.get("content-type")??"",/^text\/html\b/i,path);const html=await response.text();assert.ok(html.length>1000,path);assert.match(html,new RegExp(h1),path);assert.match(html,/aria-label="尋（たずね）トップページ"/,path)}});

test("map modes, timeline, confidence and fade change derived layer data",()=>{const records=[{date:"2012-01-01",confidence:"HIGH"},{date:"2025-01-01",confidence:"MED"}];assert.equal(visibleMapRecords(records,"all","2012-01-01","2026-12-31").length,2);assert.equal(visibleMapRecords(records,"HIGH","2012-01-01","2026-12-31").length,1);assert.equal(visibleMapRecords(records,"all","2012-01-01","2020-12-31").length,1);assert.equal(mapModeState("vector").pointRadius,8);assert.equal(mapModeState("cluster").clusterOpacity,1);assert.equal(mapModeState("heat").heatOpacity,.82);assert.equal(mapModeState("fade").pointOpacity,"fade");assert.equal(mapFadeOpacity("2012-01-01","2012-01-01","2026-01-01",true),.16);assert.equal(mapFadeOpacity("2012-01-01","2012-01-01","2026-01-01",false),1);assert.equal(timelineProfile("2026-01-01","2026-01-07").recommendedMode,"vector");assert.equal(timelineProfile("2024-01-01","2026-01-01").combinedHeat,true);assert.deepEqual(advanceTimelineWindow("2026-01-01","2026-01-07","week"),{start:"2026-01-08",end:"2026-01-14"})});

test("tips cannot advance empty steps and produces a complete browser-only summary",()=>{const steps=["緊急性","一致しなかった点","確認"];assert.equal(canAdvanceTipsStep(0,steps,{}),false);const data={対象:"対象不明",緊急性:"少し前に見た",一致しなかった点:"服装が違う"};assert.equal(canAdvanceTipsStep(0,steps,data),true);assert.equal(canAdvanceTipsStep(1,steps,data),true);assert.equal(canAdvanceTipsStep(2,steps,data),true);assert.match(buildTipsSummary(data),/一致しなかった点: 服装が違う/) });

test("wanted subjects are consistently ordered by sampled search volume",()=>{const items=[{slug:"a"},{slug:"b"},{slug:"c"}],metrics=[{entity_type:"wanted",entity_id:"a",views:99},{entity_type:"wanted_search",entity_id:"c",views:4},{entity_type:"wanted_search",entity_id:"b",views:9}];assert.deepEqual(sortByWantedSearch(items,metrics).map(item=>item.slug),["b","c","a"])});

test("shared layout, restored Tazune favicon, direct anonymous tips and menu lock stay wired",async()=>{const [shell,brand,tips,menu,css,favicon]=await Promise.all([readFile(new URL("../app/components/PublicShell.tsx",import.meta.url),"utf8"),readFile(new URL("../app/BrandMark.tsx",import.meta.url),"utf8"),readFile(new URL("../app/tips/tips-wizard.tsx",import.meta.url),"utf8"),readFile(new URL("../app/EditorialMenu.tsx",import.meta.url),"utf8"),readFile(new URL("../app/hero-adjust.css",import.meta.url),"utf8"),readFile(new URL("../public/favicon.svg",import.meta.url),"utf8")]);assert.match(shell,/className="page-content"/);assert.doesNotMatch(brand,/brand-route/);assert.doesNotMatch(tips,/手元で整理する|警察へ伝える内容|非公開審査と位置の調整/);assert.match(tips,/匿名で公開する/);assert.doesNotMatch(tips,/disabled=\{data\["緊急性"\]/);assert.match(menu,/menu-open/);assert.match(css,/z-index:\s*1000/);assert.match(favicon,/shape-rendering="geometricPrecision"/);assert.match(favicon,/>尋<\/text>/)});

test("evidence checks both claimed MIME and magic bytes",()=>{const png=new Uint8Array([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0,0,0,0]);assert.equal(evidenceType(png,"image/png"),"image/png");assert.equal(evidenceType(png,"image/jpeg"),null);assert.equal(evidenceType(new TextEncoder().encode("<svg></svg>"),"image/png"),null)});

test("production migrations seed and refresh the complete approved public registry",async()=>{const sql=await readFile(new URL("../drizzle/0003_seed_public_records.sql",import.meta.url),"utf8"),refresh=await readFile(new URL("../drizzle/0009_refresh_wanted_registry.sql",import.meta.url),"utf8"),analytics=await readFile(new URL("../drizzle/0010_naive_james_howlett.sql",import.meta.url),"utf8");assert.equal((sql.match(/INSERT OR IGNORE INTO content_records/g)||[]).length,23);assert.equal((sql.match(/'wanted'/g)||[]).length,10);assert.equal((sql.match(/'case'/g)||[]).length,3);assert.equal((sql.match(/'source'/g)||[]).length,7);assert.equal((sql.match(/'map'/g)||[]).length,3);assert.equal((refresh.match(/ON CONFLICT\(id\) DO UPDATE/g)||[]).length,17);assert.match(analytics,/CREATE TABLE `analytics_visitors`/);assert.match(analytics,/CREATE TABLE `analytics_events`/);assert.doesNotMatch(sql,/unverified|pending_public/) });

test("all ten NPA important-wanted records expose local optimized official photos",async()=>{const component=await readFile(new URL("../app/components/OfficialPhoto.tsx",import.meta.url),"utf8"),data=await readFile(new URL("../app/data/platform.ts",import.meta.url),"utf8");assert.doesNotMatch(component,/OFFICIAL PHOTO|転載条件未確認/);assert.equal((data.match(/photoUsageStatus:"cleared_for_reuse"/g)||[]).length,10);assert.equal((data.match(/officialPhotoUrl:"\/assets\/wanted\//g)||[]).length,10);for(const name of ["kogure","obara","mitate","hatta","rin","yoshiya","li-kai","ochi","miyauchi","matayoshi"]){assert.ok((await stat(new URL(`../public/assets/wanted/${name.match(/^kogure/)?"01-kogure":name.match(/^obara/)?"02-obara":name.match(/^mitate/)?"03-mitate":name.match(/^hatta/)?"04-hatta":name.match(/^rin$/)?"05-rin":name.match(/^yoshiya/)?"06-yoshiya":name.match(/^li-kai/)?"07-li-kai":name.match(/^ochi/)?"08-ochi":name.match(/^miyauchi/)?"09-miyauchi":"10-matayoshi"}.webp`,import.meta.url))).size<250000)} });

test("person and case details render real reciprocal links and record metadata",async()=>{const worker=await builtWorker(),person=await worker.fetch(new Request("http://localhost/wanted/hatta-yoichi",{headers:{accept:"text/html"}}),env,ctx),personHtml=await person.text();assert.equal(person.status,200);assert.match(personHtml,/八田 與一/);assert.match(personHtml,/cases\/beppu-university-students/);assert.match(personHtml,/八田 與一の警察公式写真/);assert.match(personHtml,/目撃情報を入力する/);assert.doesNotMatch(personHtml,/OFFICIAL PHOTO|転載条件未確認/);const caseResponse=await worker.fetch(new Request("http://localhost/cases/beppu-university-students",{headers:{accept:"text/html"}}),env,ctx),caseHtml=await caseResponse.text();assert.equal(caseResponse.status,200);assert.match(caseHtml,/wanted\/hatta-yoichi/);assert.match(caseHtml,/警察公式ソース|公式ソース/)});

test("hero uses lightweight WebP assets and does not preload MapLibre on TOP",async()=>{const enso=await stat(new URL("../public/assets/hero-enso-rich.webp",import.meta.url)),mountain=await stat(new URL("../public/assets/hero-sumi-e-mountain-wash.webp",import.meta.url));assert.ok(enso.size<400000);assert.ok(mountain.size<250000);const worker=await builtWorker(),html=await (await worker.fetch(new Request("http://localhost/",{headers:{accept:"text/html"}}),env,ctx)).text();assert.match(html,/hero-enso-rich\.webp/);assert.match(html,/hero-sumi-e-mountain-wash\.webp/);assert.doesNotMatch(html,/maplibre-gl-[A-Za-z0-9_-]+\.js/)});
