import assert from "node:assert/strict";
import {readFile,readdir} from "node:fs/promises";
import test from "node:test";
import {fileURLToPath} from "node:url";
import {Miniflare} from "miniflare";
import {createServer} from "vite";

const root=fileURLToPath(new URL("..",import.meta.url)),vite=await createServer({root,configFile:false,appType:"custom",server:{middlewareMode:true}}),platform=await vite.ssrLoadModule("/app/server/platform-db.ts"),tips=await vite.ssrLoadModule("/app/server/tips-db.ts"),analytics=await vite.ssrLoadModule("/app/server/analytics-db.ts"),tipsRoute=await vite.ssrLoadModule("/app/api/tips/route.ts"),evidenceRoute=await vite.ssrLoadModule("/app/api/tips/[id]/evidence/route.ts"),contactRoute=await vite.ssrLoadModule("/app/api/contact/route.ts");
const {listContent,saveContent,setRuntimeEnvForTests}=platform,{adminDeleteTip,adminUpdateTip,authorizedTip,createTip,editTip,evidenceObjectKeysForSubmission,listTipsForAdmin,moderateTip,privateTipDetails,withdrawTip}=tips;
const {listAnalyticsForAdmin,recordAnalyticsView,setAnalyticsExclusion}=analytics;

const pepper="test-secret-pepper";
async function testEnvironment(){const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:{DB:"tips-test"}}),DB=await mf.getD1Database("DB"),files=(await readdir(new URL("../drizzle",import.meta.url))).filter(file=>file.endsWith(".sql")).sort(),objects=new Map(),BUCKET={put:async(key,value)=>{objects.set(key,new Uint8Array(value))},delete:async key=>objects.delete(key),get:async key=>objects.has(key)?{body:objects.get(key)}:null};for(const file of files){const sql=await readFile(new URL(`../drizzle/${file}`,import.meta.url),"utf8");for(const statement of sql.split("--> statement-breakpoint").map(value=>value.trim()).filter(Boolean))await DB.prepare(statement).run()}setRuntimeEnvForTests({DB,BUCKET,TIPS_SECRET_PEPPER:pepper,TIPS_RATE_HMAC_SECRET:"test-rate-secret",TREND_HMAC_SECRET:"test-trend-secret"});return {mf,objects}}
const payload={対象:"八田 與一",緊急性:"少し前に見た",いつ:"15分前",どこ:"テスト駅前",観察条件:"20m以上",一致した点:"身長、歩き方",一致しなかった点:"服装が違う",移動:"徒歩 / 東",証拠:"なし"};

test("anonymous tips persist private contact and evidence, reload, revise, moderate, publish and withdraw",async()=>{const {mf,objects}=await testEnvironment();try{
 const directResponse=await tipsRoute.POST(new Request("http://local/api/tips",{method:"POST",headers:{origin:"http://local","content-type":"application/json","cf-connecting-ip":"203.0.113.71"},body:JSON.stringify({subjectSlug:"hatta-yoichi",caseSlug:"beppu-university-students",payload,exactLat:"35.67891",exactLon:"139.76543",geographicPrecision:"city",temporalPrecision:"period"})})),directResult=await directResponse.json();assert.equal(directResponse.status,201);assert.equal(directResult.state,"approved_public");const directMap=(await listContent(true)).find(record=>record.slug===`tip-${directResult.submissionId}`);assert.equal(directMap?.payload.source,"approved_public");assert.equal(directMap?.payload.lat,35.68);const securityRows=await (await platform.runtimeEnv()).DB.prepare("SELECT event FROM tip_security_logs WHERE submission_id=? ORDER BY event").bind(directResult.submissionId).all();assert.deepEqual(securityRows.results.map(row=>row.event),["content_duplicate","create"]);
 const created=await createTip({subjectSlug:"hatta-yoichi",caseSlug:"beppu-university-students",payload,exactLat:"35.12345",exactLon:"139.12345",geographicPrecision:"city",temporalPrecision:"period",recordType:"sighting_report",contact:{enabled:true,email:"private@example.test"}},pepper);assert.ok(created.id);assert.ok(created.editSecret.length>32);
 const first=await authorizedTip(created.id,created.editSecret,pepper);assert.equal(first?.state,"pending");assert.equal(first?.requestedPublicPrecision,"city");
 const form=new FormData(),png=new Uint8Array([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0,0,0,0]);form.append("evidence",new File([png],"camera.png",{type:"image/png"}));const uploaded=await evidenceRoute.POST(new Request(`http://local/api/tips/${created.id}/evidence`,{method:"POST",headers:{origin:"http://local",authorization:`Bearer ${created.editSecret}`},body:form}),{params:Promise.resolve({id:created.id})});assert.equal(uploaded.status,201);assert.equal(objects.size,1);const privateDetails=await privateTipDetails(created.id);assert.equal(privateDetails.contact?.email,"private@example.test");assert.equal(privateDetails.evidence[0]?.originalFilename,"camera.png");
 const contactResponse=await contactRoute.POST(new Request("http://local/api/contact",{method:"POST",headers:{origin:"http://local","content-type":"application/json","cf-connecting-ip":"203.0.113.40"},body:JSON.stringify({type:"一般問い合わせ",subject:"公開情報について",message:"掲載内容の確認をお願いします。",consent:true,replyRequested:true,email:"reader@example.test",openedAt:Date.now()-2000})}));assert.equal(contactResponse.status,201);const contactSaved=await (await platform.runtimeEnv()).DB.prepare("SELECT email,status FROM inquiries WHERE email=?").bind("reader@example.test").first();assert.equal(contactSaved?.status,"new");
 assert.equal((await recordAnalyticsView({browserId:"browser-a",path:"/",referrerPath:null,dwellSeconds:12,sampleRate:1})).accepted,true);assert.equal((await recordAnalyticsView({browserId:"browser-a",path:"/wanted/hatta-yoichi",referrerPath:"/wanted",dwellSeconds:18,sampleRate:1})).accepted,true);assert.equal((await recordAnalyticsView({browserId:"browser-a",path:"/",referrerPath:null,dwellSeconds:12,sampleRate:1})).reason,"duplicate");let analyticsData=await listAnalyticsForAdmin("browser-a");assert.match(analyticsData.currentVisitorId,/^訪問者 /);assert.equal(analyticsData.visitors.find(row=>row.display_id===analyticsData.currentVisitorId)?.total_views,2);assert.equal(analyticsData.events.length,2);const ownVisitor=analyticsData.visitors.find(row=>row.display_id===analyticsData.currentVisitorId);assert.ok(ownVisitor);assert.equal(await setAnalyticsExclusion({browserId:"browser-a",excluded:true},"admin@example.test"),true);analyticsData=await listAnalyticsForAdmin("browser-a");assert.equal(analyticsData.visitors.find(row=>row.visitor_hash===ownVisitor.visitor_hash)?.excluded,1);assert.equal(analyticsData.events.length,0);assert.equal((await recordAnalyticsView({browserId:"browser-a",path:"/map",referrerPath:null,dwellSeconds:20,sampleRate:1})).reason,"excluded");assert.equal(await setAnalyticsExclusion({visitorHash:ownVisitor.visitor_hash,excluded:false},"admin@example.test"),true);
 await saveContent({id:"map:admin-e2e",kind:"map",slug:"admin-e2e",title:"管理者E2E公開",payload:{id:"admin-e2e",subject:"hatta-yoichi",caseSlug:"beppu-university-students",label:"管理者E2E公開",lat:35.5,lon:139.5,date:"2026-08-24",confidence:"HIGH",source:"verified_source",recordType:"verified_record",geographicPrecision:"prefecture",temporalPrecision:"day",direction:0},publishState:"published"},"admin@example.test");assert.ok((await listContent(true)).some(record=>record.slug==="admin-e2e"));await saveContent({id:"map:admin-e2e",kind:"map",slug:"admin-e2e",title:"管理者E2E公開",payload:{},publishState:"withdrawn"},"admin@example.test");assert.ok(!(await listContent(true)).some(record=>record.slug==="admin-e2e"));
 const changed={...payload,"一致しなかった点":"髪型も違う"};assert.equal((await editTip(created.id,created.editSecret,pepper,changed)).kind,"updated");
 await assert.rejects(()=>moderateTip({id:created.id,action:"approve",publicPrecision:"point"},"admin@example.test"),/細かく/);assert.equal(await moderateTip({id:created.id,action:"approve",publicPrecision:"prefecture"},"admin@example.test"),true);const publicAfterApproval=await listContent(true),mapRecord=publicAfterApproval.find(record=>record.slug===`tip-${created.id}`);assert.equal(mapRecord?.payload.source,"approved_public");assert.equal(mapRecord?.payload.lat,35.1);assert.equal(mapRecord?.payload.geographicPrecision,"prefecture");
 const revised={...changed,"一致した点":"歩き方、声"};assert.equal((await editTip(created.id,created.editSecret,pepper,revised)).kind,"revision_pending");const adminData=await listTipsForAdmin(),revision=adminData.revisions.find(item=>item.submission_id===created.id&&item.state==="revision_pending");assert.equal(adminData.contacts[0]?.email,"private@example.test");assert.equal(adminData.evidence[0]?.status,"private");assert.equal(adminData.evidence[0]?.reviewState,"pending");assert.ok(revision);assert.equal(await moderateTip({id:created.id,action:"approve_revision",revisionId:String(revision.id),publicPrecision:"region"},"admin@example.test"),true);assert.equal((await authorizedTip(created.id,created.editSecret,pepper))?.payload["一致した点"],"歩き方、声");assert.equal((await authorizedTip(created.id,created.editSecret,pepper))?.geographicPrecision,"region");
 assert.equal(await withdrawTip(created.id,created.editSecret,pepper),true);assert.ok(!(await listContent(true)).some(record=>record.slug===`tip-${created.id}`));assert.equal((await authorizedTip(created.id,created.editSecret,pepper))?.state,"withdrawn");
 const unknown=await createTip({subjectSlug:null,caseSlug:null,payload:{...payload,対象:"対象不明"},exactLat:"34.68000",exactLon:"135.50000",geographicPrecision:"city",temporalPrecision:"period",recordType:"sighting_report"},pepper);await assert.rejects(()=>moderateTip({id:unknown.id,action:"approve",publicPrecision:"city"},"admin@example.test"),/対象不明/);assert.equal(await adminUpdateTip({id:unknown.id,subjectSlug:"hatta-yoichi",caseSlug:"beppu-university-students",payload:{...payload,対象:"八田 與一"},exactLat:"34.68000",exactLon:"135.50000",publicPrecision:"prefecture"},"admin@example.test"),true);assert.equal(await moderateTip({id:unknown.id,action:"approve",publicPrecision:"prefecture"},"admin@example.test"),true);assert.ok((await listContent(true)).some(record=>record.slug===`tip-${unknown.id}`));assert.equal(await moderateTip({id:unknown.id,action:"withdraw"},"admin@example.test"),true);assert.ok(!(await listContent(true)).some(record=>record.slug===`tip-${unknown.id}`));
 const keys=await evidenceObjectKeysForSubmission(created.id);assert.equal(keys.length,1);for(const key of keys)await (await platform.runtimeEnv()).BUCKET.delete(key);assert.equal(await adminDeleteTip(created.id,"admin@example.test"),true);const deleted=(await listTipsForAdmin()).submissions.find(item=>item.id===created.id);assert.equal(deleted?.state,"deleted");assert.deepEqual(deleted?.payload,{});assert.equal(deleted?.exactLat,null);assert.equal((await privateTipDetails(created.id)).contact,null);assert.equal((await privateTipDetails(created.id)).evidence.length,0);assert.equal(objects.size,0);assert.equal(await authorizedTip(created.id,created.editSecret,pepper),null);
 }finally{setRuntimeEnvForTests(undefined);await mf.dispose();await vite.close()}});
