/* eslint-disable @typescript-eslint/no-explicit-any */
import {createTip,moderateTip,type GeographicPrecision,type TemporalPrecision} from "../../server/tips-db";
import {runtimeEnv} from "../../server/platform-db";

const memoryBuckets=new Map<string,number[]>();
function error(message:string,status:number){return Response.json({error:message},{status})}
function sameSite(req:Request){const source=req.headers.get("origin")||req.headers.get("referer");if(!source)return false;try{return new URL(source).host===new URL(req.url).host}catch{return false}}
async function dailyHash(day:string,ip:string,secret:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]),signature=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(`${day}:${ip}`));return Array.from(new Uint8Array(signature),byte=>byte.toString(16).padStart(2,"0")).join("")}
function cleanPayload(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))return null;const entries=Object.entries(value as Record<string,unknown>);if(entries.length<6||entries.length>30)return null;const output:Record<string,string>={};for(const [key,raw] of entries){if(key.length>40||typeof raw!=="string"||raw.length>2000)return null;output[key]=raw.trim()}if(!output["一致した点"]||!output["一致しなかった点"]||!output["緊急性"]||!output["いつ"]||!output["どこ"])return null;return output}

export async function POST(req:Request){
 const size=Number(req.headers.get("content-length")||0);if(size>65536)return error("送信内容が大きすぎます。",413);if(!sameSite(req))return error("送信元を確認できません。",403);if(!(req.headers.get("content-type")||"").includes("application/json"))return error("Content-Typeが不正です。",415);
 let body:any;try{body=await req.json()}catch{return error("JSONが不正です。",400)}if(body.website)return Response.json({ok:true});const payload=cleanPayload(body.payload);if(!payload)return error("整理内容を確認してください。",400);
 const requestedPrecision=String(body.geographicPrecision||"") as GeographicPrecision,geographicPrecision:GeographicPrecision=requestedPrecision==="point"?"city":requestedPrecision,temporalPrecision=String(body.temporalPrecision||"") as TemporalPrecision;if(!(["point","city","prefecture","region"] as string[]).includes(requestedPrecision)||!(["exact","day","month","period"] as string[]).includes(temporalPrecision))return error("位置・時間の精度を確認してください。",400);
 const exactLat=body.exactLat==null?null:String(body.exactLat),exactLon=body.exactLon==null?null:String(body.exactLon);if(!exactLat||!exactLon||!Number.isFinite(Number(exactLat))||!Number.isFinite(Number(exactLon)))return error("サイトへ残す場合は、現在地取得または地図タップで管理用の位置を指定してください。",400);
 const env=await runtimeEnv();if(!env.DB||!env.TIPS_SECRET_PEPPER||!env.TIPS_RATE_HMAC_SECRET)return error("現在、サイト保存を一時停止しています。整理・コピー・印刷は利用できます。",503);if(Boolean(env.TURNSTILE_SITE_KEY)!==Boolean(env.TURNSTILE_SECRET))return error("投稿のセキュリティ設定を確認中です。",503);
 const ip=req.headers.get("cf-connecting-ip")||"local",day=new Date().toISOString().slice(0,10),ipHash=await dailyHash(day,ip,env.TIPS_RATE_HMAC_SECRET),now=Date.now(),recent=(memoryBuckets.get(ipHash)||[]).filter(value=>now-value<86400000);if(recent.filter(value=>now-value<3600000).length>=3||recent.length>=8)return error("送信回数の上限に達しました。時間をおいてください。",429);
 const counts=await env.DB.prepare("SELECT SUM(CASE WHEN created_at>=datetime('now','-1 hour') THEN 1 ELSE 0 END) AS hour_count,COUNT(*) AS day_count FROM tip_security_logs WHERE daily_ip_hash=? AND event='create' AND created_at>=datetime('now','-1 day')").bind(ipHash).first<{hour_count:number;day_count:number}>();if(Number(counts?.hour_count||0)>=3||Number(counts?.day_count||0)>=8)return error("送信回数の上限に達しました。時間をおいてください。",429);
 const contentHash=await dailyHash(day,JSON.stringify([String(body.subjectSlug||"unknown"),Number(exactLat).toFixed(3),Number(exactLon).toFixed(3),payload]),env.TIPS_RATE_HMAC_SECRET),duplicate=await env.DB.prepare("SELECT id FROM tip_security_logs WHERE daily_ip_hash=? AND event='content_duplicate' AND created_at>=datetime('now','-1 day') LIMIT 1").bind(contentHash).first(),globalBurst=await env.DB.prepare("SELECT COUNT(*) AS count FROM tip_security_logs WHERE event='create' AND created_at>=datetime('now','-10 minutes')").first<{count:number}>();if(duplicate)return error("同じ内容はすでに送信されています。",409);if(Number(globalBurst?.count||0)>=120)return error("現在混み合っています。時間をおいてください。",429);
 let turnstile=true;if(env.TURNSTILE_SECRET){const form=new FormData();form.set("secret",env.TURNSTILE_SECRET);form.set("response",String(body.turnstileToken||""));form.set("remoteip",ip);const result:any=await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify",{method:"POST",body:form}).then(response=>response.json()).catch(()=>({success:false}));turnstile=Boolean(result.success)}if(!turnstile)return error("セキュリティ確認に失敗しました。",403);
 const created=await createTip({subjectSlug:body.subjectSlug||null,caseSlug:body.caseSlug||null,payload,exactLat,exactLon,geographicPrecision,temporalPrecision,recordType:"sighting_report"},env.TIPS_SECRET_PEPPER),expires=new Date(Date.now()+30*86400000).toISOString();await env.DB.batch([env.DB.prepare("INSERT INTO tip_security_logs (id,submission_id,daily_ip_hash,event,turnstile_success,created_at,expires_at) VALUES (?,?,?,?,?,CURRENT_TIMESTAMP,?)").bind(crypto.randomUUID(),created.id,ipHash,"create",turnstile?1:0,expires),env.DB.prepare("INSERT INTO tip_security_logs (id,submission_id,daily_ip_hash,event,turnstile_success,created_at,expires_at) VALUES (?,?,?,?,?,CURRENT_TIMESTAMP,?)").bind(crypto.randomUUID(),created.id,contentHash,"content_duplicate",turnstile?1:0,expires)]);let state="pending";if(body.subjectSlug){try{if(await moderateTip({id:created.id,action:"approve",publicPrecision:geographicPrecision},"anonymous-auto"))state="approved_public"}catch{state="pending"}}recent.push(now);memoryBuckets.set(ipHash,recent);return Response.json({ok:true,state,submissionId:created.id,editSecret:created.editSecret,recoveryCode:created.recoveryCode,managementPath:`/tips/manage/${created.id}#secret=${created.editSecret}`},{status:201,headers:{"cache-control":"no-store"}})
}
