import {authorizedTip,editTip,privateTipDetails,withdrawTip} from "../../../server/tips-db";
import {runtimeEnv} from "../../../server/platform-db";

function bearer(req:Request){const value=req.headers.get("authorization")||"";return value.startsWith("Bearer ")?value.slice(7):""}
function sameSite(req:Request){const source=req.headers.get("origin")||req.headers.get("referer");if(!source)return false;try{return new URL(source).host===new URL(req.url).host}catch{return false}}
function jsonError(message:string,status:number){return Response.json({error:message},{status})}
function validPayload(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))return false;const entries=Object.entries(value as Record<string,unknown>);return entries.length>=6&&entries.length<=30&&entries.every(([key,item])=>key.length<=40&&typeof item==="string"&&item.length<=2000)&&Boolean((value as Record<string,string>)["一致した点"]&&(value as Record<string,string>)["一致しなかった点"])}
async function context(req:Request,params:Promise<{id:string}>){const {id}=await params,env=await runtimeEnv();if(!env.TIPS_SECRET_PEPPER)return null;const secret=bearer(req);if(!secret)return null;const tip=await authorizedTip(id,secret,env.TIPS_SECRET_PEPPER);return tip?{id,tip,secret,env}:null}

export async function GET(req:Request,{params}:{params:Promise<{id:string}>}){const result=await context(req,params);if(!result)return jsonError("管理情報を確認できません。",401);return Response.json({submission:result.tip,...await privateTipDetails(result.id)},{headers:{"cache-control":"no-store"}})}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){if(Number(req.headers.get("content-length")||0)>65536)return jsonError("更新内容が大きすぎます。",413);if(!sameSite(req))return jsonError("送信元を確認できません。",403);if(!(req.headers.get("content-type")||"").includes("application/json"))return jsonError("Content-Typeが不正です。",415);const result=await context(req,params);if(!result)return jsonError("管理情報を確認できません。",401);const body=await req.json() as {action?:string;payload?:Record<string,string>};if(body.action!=="edit"||!validPayload(body.payload))return jsonError("更新内容を確認してください。",400);const saved=await editTip(result.id,result.secret,result.env.TIPS_SECRET_PEPPER!,body.payload!);if(saved.kind==="unauthorized")return jsonError("管理情報を確認できません。",401);if(saved.kind==="locked")return jsonError("現在の状態では直接編集できません。",409);return Response.json({ok:true,result:saved.kind,submission:(await authorizedTip(result.id,result.secret,result.env.TIPS_SECRET_PEPPER!))||result.tip})}
export async function DELETE(req:Request,{params}:{params:Promise<{id:string}>}){if(!sameSite(req))return jsonError("送信元を確認できません。",403);const result=await context(req,params);if(!result)return jsonError("管理情報を確認できません。",401);return await withdrawTip(result.id,result.secret,result.env.TIPS_SECRET_PEPPER!)?Response.json({ok:true,state:"withdrawn"}):jsonError("取り下げできませんでした。",409)}
