/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {mapRecords as fallbackRecords,subjects,cases} from "../data/platform";
import {OfficialPhoto} from "../components/OfficialPhoto";
import {PersonPicker} from "../components/PersonPicker";
import {advanceTimelineWindow,mapDateExtent,mapFadeOpacity,mapModeState,parseMapDate,timelineProfile,timelineRangeForPreset,visibleMapRecords,type MapMode,type TimelinePreset} from "../lib/map-state";

type Point=(typeof fallbackRecords)[number];
type ViewName="world"|"japan"|"hokkaido-tohoku"|"kanto"|"chubu"|"kinki"|"chugoku-shikoku"|"kyushu-okinawa";
type MapTheme="light"|"dark";
const views:Record<ViewName,{label:string;center:[number,number];zoom:number}>={
 world:{label:"WORLD",center:[20,24],zoom:1.15},japan:{label:"JAPAN",center:[138,36.2],zoom:4.3},
 "hokkaido-tohoku":{label:"北海道・東北",center:[141.2,40.7],zoom:5.5},kanto:{label:"関東",center:[139.5,36],zoom:6.4},chubu:{label:"中部",center:[137.2,36],zoom:5.9},kinki:{label:"近畿",center:[135.4,34.8],zoom:6.2},"chugoku-shikoku":{label:"中国・四国",center:[133.5,34.2],zoom:5.8},"kyushu-okinawa":{label:"九州・沖縄",center:[130.4,31.7],zoom:5.25},
};
const modeLabels:Record<MapMode,{primary:string;secondary:string}>={vector:{primary:"方向",secondary:"VECTOR"},cluster:{primary:"集約",secondary:"CLUSTER"},heat:{primary:"分布",secondary:"HEAT"},fade:{primary:"時間差",secondary:"FADE"}};
const presetLabels:Record<TimelinePreset,string>={"7d":"7日","30d":"30日","6m":"半年","1y":"1年",all:"全期間",custom:"期間指定"};
const styleUrls:Record<MapTheme,string>={light:"https://tiles.openfreemap.org/styles/positron",dark:"https://tiles.openfreemap.org/styles/dark"};
const recordLabels:Record<string,string>={verified_record:"公式確認記録",official_event:"公式発表の出来事",sighting_aggregate:"審査済み地域集計",approved_public:"審査済み公開情報"},precisionLabels:Record<string,string>={point:"地点",city:"市区町村単位",prefecture:"都道府県単位",region:"地方単位"},temporalLabels:Record<string,string>={exact:"正確な日時",day:"日単位",month:"月単位",period:"期間情報"},confidenceLabels:Record<string,string>={HIGH:"公式情報を確認",MED:"審査・根拠を確認"},sourceLabels:Record<string,string>={verified_source:"公式情報を確認済み",approved_public:"管理者審査済み"};
function initialParam(name:string){return typeof window!=="undefined"?new URLSearchParams(window.location.search).get(name)||"all":"all"}
function emptyCollection(){return {type:"FeatureCollection",features:[]}}

export function InvestigationMap(){
 const el=useRef<HTMLDivElement>(null),map=useRef<any>(null),recordsRef=useRef<Point[]>(fallbackRecords),geojsonRef=useRef<any>(emptyCollection()),presetRef=useRef<TimelinePreset>("all");
 const extent=mapDateExtent(fallbackRecords);
 const [styleEpoch,setStyleEpoch]=useState(0),[mode,setMode]=useState<MapMode>("heat"),[autoMode,setAutoMode]=useState(true),[theme,setTheme]=useState<MapTheme>("light"),[view,setView]=useState<ViewName>("japan");
 const [subject,setSubject]=useState(()=>initialParam("subject")),[caseSlug,setCaseSlug]=useState(()=>initialParam("case")),[confidence,setConfidence]=useState("all"),[preset,setPreset]=useState<TimelinePreset>("all"),[start,setStart]=useState(extent.start),[end,setEnd]=useState(extent.end);
 const [records,setRecords]=useState<Point[]>(fallbackRecords),[selected,setSelected]=useState<Point|null>(null),[playing,setPlaying]=useState(false),[dataSource,setDataSource]=useState("静的データ");
 const profile=useMemo(()=>timelineProfile(start,end),[start,end]);
 const activeMode=autoMode?profile.recommendedMode:mode;

 useEffect(()=>{presetRef.current=preset},[preset]);
 useEffect(()=>{const q=new URLSearchParams({kind:"map"});if(subject!=="all")q.set("subject",subject);if(caseSlug!=="all")q.set("case",caseSlug);fetch(`/api/public-data?${q}`,{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then((j:{records:Array<{payload:Point}>})=>{const next=j.records.map(x=>x.payload);recordsRef.current=next;setRecords(next);setDataSource("公開DB");if(presetRef.current==="all"){const range=mapDateExtent(next);setStart(range.start);setEnd(range.end)}}).catch(()=>{const next=fallbackRecords.filter(x=>(subject==="all"||x.subject===subject)&&(caseSlug==="all"||x.caseSlug===caseSlug));recordsRef.current=next;setRecords(next);setDataSource("静的公式データ");if(presetRef.current==="all"){const range=mapDateExtent(next);setStart(range.start);setEnd(range.end)}})},[subject,caseSlug]);
 const visible=useMemo(()=>visibleMapRecords(records,confidence,start,end),[records,confidence,start,end]);
 const displayedSelected=selected&&visible.some(record=>record.id===selected.id)?selected:null;
 const geojson=useMemo(()=>({type:"FeatureCollection",features:visible.map(p=>({type:"Feature",geometry:{type:"Point",coordinates:[p.lon,p.lat]},properties:{...p,timestamp:parseMapDate(p.date)?.getTime()||0,fadeOpacity:mapFadeOpacity(p.date,start,end,activeMode==="fade")}}))}),[visible,start,end,activeMode]);
 useEffect(()=>{geojsonRef.current=geojson},[geojson]);

 const installLayers=useCallback((m:any)=>{if(m.getSource("records"))return;m.addSource("records",{type:"geojson",data:geojsonRef.current} as any);m.addSource("records-cluster",{type:"geojson",data:geojsonRef.current,cluster:true,clusterRadius:52,clusterMaxZoom:11} as any);m.addLayer({id:"heat",type:"heatmap",source:"records",maxzoom:12,paint:{"heatmap-weight":["interpolate",["linear"],["get","fadeOpacity"],.16,.2,1,1],"heatmap-intensity":1.25,"heatmap-radius":34,"heatmap-opacity":0}} as any);m.addLayer({id:"clusters",type:"circle",source:"records-cluster",filter:["has","point_count"],paint:{"circle-color":"#a78b57","circle-radius":["step",["get","point_count"],19,5,26],"circle-opacity":0,"circle-stroke-width":1,"circle-stroke-color":"#24231f"}} as any);m.addLayer({id:"cluster-count",type:"symbol",source:"records-cluster",filter:["has","point_count"],layout:{"text-field":["get","point_count_abbreviated"],"text-size":11,"visibility":"none"},paint:{"text-color":"#faf9f5"}} as any);m.addLayer({id:"points",type:"circle",source:"records",paint:{"circle-color":"#a78b57","circle-stroke-color":"#24231f","circle-stroke-width":1,"circle-radius":8,"circle-opacity":1}} as any);m.addLayer({id:"directions",type:"symbol",source:"records",layout:{"text-field":"↑","text-size":22,"text-rotate":["get","direction"],"text-offset":[0,-1.05],"visibility":"none"},paint:{"text-color":"#8f7241","text-halo-color":"#f7f4ec","text-halo-width":1}} as any);setStyleEpoch(value=>value+1)},[]);
 const update=useCallback(()=>{const m=map.current;if(!styleEpoch||!m||!m.getSource("records"))return;if(!m.getLayer("cluster-points"))m.addLayer({id:"cluster-points",type:"circle",source:"records-cluster",filter:["!",["has","point_count"]],paint:{"circle-color":"#a78b57","circle-stroke-color":"#24231f","circle-stroke-width":1,"circle-radius":6,"circle-opacity":0}} as any);const state=mapModeState(activeMode,autoMode&&profile.combinedHeat);(m.getSource("records") as any).setData(geojson);(m.getSource("records-cluster") as any).setData(geojson);m.setPaintProperty("heat","heatmap-opacity",state.heatOpacity);m.setPaintProperty("clusters","circle-opacity",state.clusterOpacity);m.setPaintProperty("cluster-points","circle-opacity",activeMode==="cluster"?1:0);m.setLayoutProperty("cluster-count","visibility",state.clusterLabels);m.setPaintProperty("points","circle-opacity",state.pointOpacity==="fade"?["get","fadeOpacity"]:state.pointOpacity);m.setPaintProperty("points","circle-radius",state.pointRadius);m.setLayoutProperty("directions","visibility",state.directionVisibility);const dateFilter=["all",[">=",["get","timestamp"],parseMapDate(start)?.getTime()||0],["<=",["get","timestamp"],parseMapDate(end)?.getTime()||Date.now()]];m.setFilter("points",dateFilter);m.setFilter("directions",dateFilter)},[styleEpoch,activeMode,autoMode,profile.combinedHeat,geojson,start,end]);
 function focus(next:ViewName){setView(next);const v=views[next];map.current?.flyTo({center:v.center,zoom:v.zoom,duration:700})}
 function selectPreset(next:TimelinePreset){setPreset(next);setPlaying(false);if(next!=="custom"){const range=timelineRangeForPreset(next,records);setStart(range.start);setEnd(range.end);setAutoMode(true)}}
 function setCustom(which:"start"|"end",value:string){setPreset("custom");setAutoMode(true);setPlaying(false);if(which==="start")setStart(value);else setEnd(value)}

 useEffect(()=>{let alive=true;import("maplibre-gl").then(({default:maplibregl})=>{if(!alive||!el.current||map.current)return;const m=new maplibregl.Map({container:el.current,style:styleUrls.light,center:views.japan.center,zoom:views.japan.zoom,maxZoom:17});map.current=m;m.addControl(new maplibregl.NavigationControl({visualizePitch:true}),"top-right");m.on("style.load",()=>installLayers(m));m.on("click","points",(e:any)=>{const id=e.features?.[0]?.properties?.id;setSelected(recordsRef.current.find(x=>x.id===id)||fallbackRecords.find(x=>x.id===id)||null)});m.on("click","clusters",(e:any)=>{const f=e.features?.[0],clusterId=f?.properties?.cluster_id;(m.getSource("records-cluster") as any)?.getClusterExpansionZoom(clusterId,(err:any,zoom:number)=>{if(!err&&f)m.easeTo({center:(f.geometry as any).coordinates,zoom})})})});return()=>{alive=false;map.current?.remove();map.current=null}},[installLayers]);
 useEffect(()=>{update()},[update]);
 useEffect(()=>{if(!map.current)return;map.current.setStyle(styleUrls[theme])},[theme]);
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>{const next=advanceTimelineWindow(start,end,profile.playStep);const latest=mapDateExtent(records).end;if(next.start>latest){const reset=timelineRangeForPreset(preset==="custom"?"all":preset,records);setStart(reset.start);setEnd(reset.end)}else{setStart(next.start);setEnd(next.end)}},800);return()=>clearInterval(timer)},[playing,start,end,profile.playStep,records,preset]);

 return <section className="map-workspace">
  <div className="map-scale" aria-label="地図の範囲"><button className={view==="world"?"active":""} onClick={()=>focus("world")}>WORLD</button><span>→</span><button className={view==="japan"?"active":""} onClick={()=>focus("japan")}>JAPAN</button><span>→</span><label>地域<select value={view.includes("-")?view:"japan"} onChange={e=>focus(e.target.value as ViewName)}><option value="japan">地域を選択</option>{Object.entries(views).filter(([key])=>key!=="world"&&key!=="japan").map(([key,value])=><option value={key} key={key}>{value.label}</option>)}</select></label><div className="map-theme" role="group" aria-label="地図の配色"><button className={theme==="light"?"active":""} aria-label="明るい地図で表示" aria-pressed={theme==="light"} onClick={()=>setTheme("light")}><b>白図</b><small>LIGHT</small></button><button className={theme==="dark"?"active":""} aria-label="暗い地図で表示" aria-pressed={theme==="dark"} onClick={()=>setTheme("dark")}><b>墨図</b><small>DARK</small></button></div></div>
  <div className="map-toolbar"><div className="map-modes" role="group" aria-label="表示モード">{(Object.keys(modeLabels) as MapMode[]).map(value=><button className={activeMode===value?"active":""} aria-pressed={activeMode===value} onClick={()=>{setMode(value);setAutoMode(false)}} key={value}><b>{modeLabels[value].primary}</b><small>{modeLabels[value].secondary}</small></button>)}</div><PersonPicker value={subject} includeAll onChange={value=>{setSubject(value);setCaseSlug("all")}}/><label>関連事件<select value={caseSlug} onChange={e=>{setCaseSlug(e.target.value);setSubject("all")}}><option value="all">全事件</option>{cases.map(item=><option value={item.slug} key={item.slug}>{item.title}</option>)}</select></label><label>情報確度 <span className="help-mark" title="人物の本人一致率ではなく、その記録の根拠・確認状態です。" aria-label="情報確度は本人一致率ではなく、記録の根拠と確認状態を示します">?</span><select value={confidence} onChange={e=>setConfidence(e.target.value)}><option value="all">すべて</option><option value="HIGH">公式確認</option><option value="MED">審査済み公開</option></select></label></div>
  <div className="timeline-presets" role="group" aria-label="表示期間">{(Object.keys(presetLabels) as TimelinePreset[]).map(value=><button className={preset===value?"active":""} aria-pressed={preset===value} onClick={()=>selectPreset(value)} key={value}>{presetLabels[value]}</button>)}</div>
  <div className="timeline-range"><label>開始<input type="date" value={start} max={end} onChange={e=>setCustom("start",e.target.value)}/></label><span>—</span><label>終了<input type="date" value={end} min={start} onChange={e=>setCustom("end",e.target.value)}/></label><button onClick={()=>setPlaying(value=>!value)} aria-pressed={playing}>{playing?"停止":"再生"}<small>PLAY / {profile.playStep.toUpperCase()}</small></button><output>{visible.length}件 / {profile.granularity}{autoMode?" / 自動表示":" / 手動表示"}</output></div>
  <div className={`map-frame map-frame--${theme}`}><div ref={el} className="real-map" aria-label="公開された記録を場所と時間から辿る地図"/><aside className="map-detail"><p className="kicker">{modeLabels[activeMode].primary} / {modeLabels[activeMode].secondary} / {visible.length} RECORDS / {dataSource}</p>{displayedSelected?(()=>{const person=subjects.find(x=>x.slug===displayedSelected.subject);return <>{person&&<OfficialPhoto subject={person} compact/>}<h2>{displayedSelected.label}</h2><dl><dt>対象人物</dt><dd>{person?.name||"対象不明"}</dd><dt>手配元</dt><dd>{person?.agency||"—"}</dd><dt>関連事件</dt><dd>{cases.find(x=>x.slug===displayedSelected.caseSlug)?.title}</dd><dt>記録種別</dt><dd>{recordLabels[displayedSelected.recordType||"verified_record"]||"公開記録"}</dd><dt>日付</dt><dd>{displayedSelected.date} / {temporalLabels[displayedSelected.temporalPrecision||"day"]}</dd><dt>位置精度</dt><dd>{precisionLabels[displayedSelected.geographicPrecision||"point"]}</dd><dt>情報確度</dt><dd>{confidenceLabels[displayedSelected.confidence]||"根拠を確認"}<br/><small>{sourceLabels[displayedSelected.source]||"公開条件を確認済み"}</small></dd><dt>方向</dt><dd><span className="direction" style={{transform:`rotate(${displayedSelected.direction}deg)`}}>↑</span> {displayedSelected.direction}°</dd></dl>{person&&<a className="text-arrow" href={person.photoSourceUrl} target="_blank" rel="noreferrer">公式Source・写真を確認 ↗</a>}</>})():<p>地点を選択すると、公式情報との関係と記録の根拠・確認状態を表示します。</p>}</aside></div>
  <p className="map-disclosure">公式確認済み記録と、登録済み人物への匿名目撃記録を表示します。正確な入力位置・Evidenceは表示しません。</p>
 </section>
}
