/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
"use client";
import {useEffect,useState} from "react";
type Submission={id:string;state:string;payload:Record<string,string>;revision:number;updatedAt:string;geographicPrecision:string;temporalPrecision:string};
type Contact={email:string|null;phone:string|null;consent:boolean};type Evidence={id:string;originalFilename:string;mime:string;fileSize:number;sha256:string;uploadedAt:string};
const editable=["対象","緊急性","いつ","どこ","観察条件","一致した点","一致しなかった点","移動","証拠"];
export function TipManager({id}:{id:string}){const [secret,setSecret]=useState(""),[submission,setSubmission]=useState<Submission|null>(null),[contact,setContact]=useState<Contact|null>(null),[evidence,setEvidence]=useState<Evidence[]>([]),[recovery,setRecovery]=useState(""),[message,setMessage]=useState("管理情報を確認しています…"),[busy,setBusy]=useState(false);
 async function load(value:string){const response=await fetch(`/api/tips/${id}`,{headers:{authorization:`Bearer ${value}`},cache:"no-store"}),result=await response.json() as {submission?:Submission;contact?:Contact|null;evidence?:Evidence[];error?:string};if(!response.ok)throw new Error(result.error||"管理情報を確認できません。");setSubmission(result.submission||null);setContact(result.contact||null);setEvidence(result.evidence||[]);setMessage("保存済み情報・非公開MetadataをD1から再取得しました。")}
 useEffect(()=>{const raw=new URLSearchParams(location.hash.slice(1)).get("secret")||"";if(raw){setSecret(raw);history.replaceState(null,"",location.pathname);load(raw).catch(error=>setMessage(error instanceof Error?error.message:"読み込めませんでした。"))}else setMessage("管理リンクのsecret、または復旧コードが必要です。")},[id]);
 async function save(){if(!submission||!secret)return;setBusy(true);try{const response=await fetch(`/api/tips/${id}`,{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${secret}`},body:JSON.stringify({action:"edit",payload:submission.payload})}),result=await response.json() as {error?:string;result?:string};if(!response.ok)throw new Error(result.error||"保存できませんでした。");await load(secret);setMessage(result.result==="revision_pending"?"公開内容は直接上書きせず、審査待ちRevisionとして保存しました。":"変更を保存し、D1から再取得しました。") }catch(error){setMessage(error instanceof Error?error.message:"保存できませんでした。")}finally{setBusy(false)}}
 async function recover(){setBusy(true);try{const response=await fetch(`/api/tips/${id}/recover`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({recoveryCode:recovery})}),result=await response.json() as {editSecret?:string;error?:string};if(!response.ok||!result.editSecret)throw new Error(result.error||"復旧できませんでした。");setSecret(result.editSecret);await load(result.editSecret);setMessage("管理secretを再発行しました。新しい管理リンクを保存してください。")}catch(error){setMessage(error instanceof Error?error.message:"復旧できませんでした。")}finally{setBusy(false)}}
 async function withdraw(){if(!secret||!window.confirm("この投稿を取り下げます。公開レコードがある場合も非表示になります。よろしいですか？"))return;setBusy(true);try{const response=await fetch(`/api/tips/${id}`,{method:"DELETE",headers:{authorization:`Bearer ${secret}`}}),result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"取り下げできませんでした。");await load(secret);setMessage("取り下げました。公開レコードがある場合も非表示になり、監査履歴だけを保持します。")}catch(error){setMessage(error instanceof Error?error.message:"取り下げできませんでした。")}finally{setBusy(false)}}
 if(!submission)return <section className="tip-manager"><p role="status">{message}</p><div className="recovery-form"><h2>復旧コードで管理を再開</h2><p>管理リンクを失った場合だけ利用してください。新しいsecretが発行され、以前のリンクは無効になります。</p><label>復旧コード<input value={recovery} onChange={event=>setRecovery(event.target.value)}/></label><button disabled={busy||!recovery} onClick={recover}>管理情報を復旧</button></div></section>;
 return <section className="tip-manager"><div className="manager-status"><span>{submission.state}</span><b>Revision {submission.revision}</b><time>{submission.updatedAt}</time></div><p role="status">{message}</p>{editable.map(key=><label key={key}>{key}<textarea value={submission.payload[key]||""} onChange={event=>setSubmission({...submission,payload:{...submission.payload,[key]:event.target.value}})}/></label>)}{(contact||evidence.length>0)&&<section className="private-metadata"><h2>非公開情報</h2>{contact&&<p>追加連絡：{contact.email||"メールなし"} / {contact.phone||"電話なし"}</p>}{evidence.map(file=><p key={file.id}><b>{file.originalFilename}</b><br/><small>{file.mime} / {(file.fileSize/1024/1024).toFixed(1)}MB / SHA-256 {file.sha256.slice(0,16)}…</small></p>)}<small>Public画面・公開Mapには表示されません。</small></section>}<div className="action-row"><button disabled={busy||submission.state==="withdrawn"} onClick={save}>変更を保存して再取得</button><button disabled={busy||submission.state==="withdrawn"} onClick={withdraw}>取り下げる</button><button onClick={()=>navigator.clipboard.writeText(`${location.origin}${location.pathname}#secret=${secret}`)}>新しい管理リンクをコピー</button></div>{submission.state==="approved_public"&&<p className="manager-note">公開済み情報の編集は公開内容を直接上書きせず、revision_pendingとして管理者の再審査へ送られます。</p>}</section>}
